### ISSUE TITLE
Email address should be used instead of the username to login. 

### ISSUE THREAD

**Issue by Ishmeetsingh97** [amahi/android#106]
Email address should be used instead of the username to login to implement features such as using facebook sdk ,google sdk to login without user inputting the email id and password.

**Comment by cpg** [comment]
I believe username or email is possible.

However, one needs to have an Amahi server to use the app, therefore one has to have an Amahi.org account. It does not make much sense to adopt other logins. If we did, we would just end up with tons of junk users that would inevitably be disappointed and possibly angry, leaving bad reviews.
