### ISSUE TITLE
Application crashing when the User login

### ISSUE THREAD

**Issue by nikhilbalyan** [amahi/android#126]
Problem Description:
When i signed out of the application and then signed in into the application it closed as soon as i clicked signin button after filling correct details(Not crashing when the details are correct).
Expected behavior:
It should not close but instead take user to the launching/main activity

I would love to discuss this issue more

**Comment by csoni111** [comment]
There's already an issue #116 and a fix pr #117 open for this. Please close this duplicate issue!
