### ISSUE TITLE
Disabling the viewPager slide action when zoomed in.

### ISSUE THREAD

**Issue by octacode** [amahi/android#128]
It really makes difficult to zoom into the corners and navigate inside the zoomed picture properly because most of the time if we try to reach the corner of the zoomed picture the picture slides to the next. Apps like Google Photos don't allow this, rather they disable the slide action when zoomed in.

I'd like to work on this.

**Comment by cpg** [comment]
In so far as I can tell, this is not a problem currently. I can zoom and slide without sliding to the next.

**Comment by octacode** [comment]
@cpg The best example is Google photos. If we zoom in a picture they disable the sliding action and I think it's better because it provides better navigation inside the zoomed in picture.

**Comment by octacode** [comment]
I think we can postpone this issue. Closing this for now.
