### ISSUE TITLE
could not set up

### ISSUE THREAD

**Issue by DravitLochan** [amahi/android#13]
could not build the project. it says 
"Error:Failed to open zip file.
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)
Re-download dependencies and sync project (requires network)"

any help?

**Comment by megabitdragon** [comment]
I can't reproduce this. Make sure you have internet connection and retry.

**Comment by DravitLochan** [comment]
well i am connected to internet.

**Comment by cpg** [comment]
Ask in the Amahi Android Google group. Or IRC to other interested parties.
