### ISSUE TITLE
layout for movies is not right

### ISSUE THREAD

**Issue by cpg** [amahi/android#130]
This is what I see on my phone -- a [single column of movie posters](https://www.dropbox.com/s/06ong0misn95n1z/Screen%20Shot%202017-03-20%20at%204.50.43%20PM.png?dl=0) when it could well be 2 columns.

Maybe reduce the size a bit?

In vertical it looks ok with 3 columns.

My phone's resolution is 1280x720.

**Comment by octacode** [comment]
What I feel is displaying 2 icons will be better and I think I can work on this issue.
Thanks
