### ISSUE TITLE
special characters test fails with "Connection Error"

### ISSUE THREAD

**Issue by cpg** [amahi/android#131]
we put a `special-characters` folder in the demo server. it appears to show a "connection error" in the app. it could be the origin server or the app.

needs to be investigated. in a common file browser, it looks more or less [like this](https://www.dropbox.com/s/xjo4kj4ds7ana61/Screen%20Shot%202017-03-20%20at%205.13.07%20PM.png?dl=0).

**Comment by adithya321** [comment]
There is a file named 'test ".png' in that folder. The double quote in the file name breaks the JSON structure.
```
com.google.gson.stream.MalformedJsonException: Unterminated object at line 6 column 19 path $[4].name
```

<img width="835" alt="jsonexception" src="https://cloud.githubusercontent.com/assets/3854934/24132300/882a8c96-0e1a-11e7-8d00-2bacbe97ce69.png">

I guess it will work if that file is removed.

**Comment by csoni111** [comment]
Or that double quotes must be escaped on the server while creating the json! That would solve the problem.
Like this : `"test \".png"`

**Comment by cpg** [comment]
Thanks for the debugging. The name of the file was not escaped.

This has been fixed in the server. All files seem to display ok, except the one starting with &. Not sure yet what is going on with that one.

Will release widely to the Amahi user base in the next release. The welcome server is updated now.
