### ISSUE TITLE
Application crashed on clicking the next song icon

### ISSUE THREAD

**Issue by nikhilbalyan** [amahi/android#136]
Problem description:
app crash when the user play the next song.

Steps to reproduce:
step:-1 login to application
step:-2 click share menu item from the navigation bar
step:-3 click the demo
step:-4 click the music
step:-5 click the 02 Meghan Trainor song
step:-6 click play the next song icon

And the application crash as soon as user click the next song icon or the previous song icon
I would love to work on this issue

**Comment by cpg** [comment]
I can reproduce this.

**Comment by harshvardhanpro** [comment]
@nikhilbalyan are you working on this issue ?

**Comment by joydeepsaha05** [comment]
@cpg This can be closed.
