### ISSUE TITLE
Play next and previous song control missing

### ISSUE THREAD

**Issue by nikhilbalyan** [amahi/android#137]
Steps to reproduce:
Step:-1 login into Amahi
Step:-2 click on the share menu from navigation bar
Step:-4 click on videos from the list of options
Step:-5 click on any of video we will not see a control for playing the next and previous video in the  media        player.

Expected behavior:
play  next and previous button must be there like in music subcategory inside demo

**Comment by harshvardhanpro** [comment]
@nikhilbalyan are you working on this issue or should ? if not, i would like to..

**Comment by nikhilbalyan** [comment]
@harshvardhanpro sorry to inform you that i have already started working on this feature you may look at other unassigned features or maybe open another issue.

**Comment by cpg** [comment]
Abandoned
