### ISSUE TITLE
Setting up project

### ISSUE THREAD

**Issue by jainadit27** [amahi/android#14]
I have the code up and running. Where can I find URL, ID and SECRET to be updated in api.properties? I have registered on Amahi website.

**Comment by mehtamanan0** [comment]
Even i had the same problem while setting up cpg shared it
Here's the link:
http://alpha.amahi.org/tmp/api.properties

**Comment by cpg** [comment]
@mehtamanan0 In the file, it makes it very clear that this file should not be shared with others. And you were told when the URL was given to you. These sort of API keys are meant to not be public.

**Comment by mehtamanan0** [comment]
@cpg im so sorry for this mistake this will not happen again.

**Comment by jainadit27** [comment]
@cpg Can you please share the file

**Comment by vjs3** [comment]
@cpg please provide the file so that I can run the application.
