### ISSUE TITLE
Cardview Material design enhancement

### ISSUE THREAD

**Issue by nikhilbalyan** [amahi/android#146]
Current scenario:
We are using the textview to display the items such as video, demo and music 

Proposed scenario
Placing the demo, video and introduction option textview inside the cardview to enhance the UI and provide elevation to  them and following the similar pattern inside the sub activities inside of them.

I would love to work on this issue

**Comment by cpg** [comment]
I am not sure I follow, because video, etc. are full-screen things (except for when the controls are up). Maybe show what it would look like?

**Comment by nikhilbalyan** [comment]
@cpg you are right they are the full-screen things. I was just thinking from a different perspective as shown in following images right now in most of them we are showing options just with textview which can be wrapped around a cardview to give better look and feel.
![screenshot_2017-03-24-11-07-46](https://cloud.githubusercontent.com/assets/12967091/24281945/8762df60-1082-11e7-86f6-a17e0406115b.png)
![screenshot_2017-03-24-11-07-50](https://cloud.githubusercontent.com/assets/12967091/24281951/8c98e088-1082-11e7-88fc-635e01605301.png)
![screenshot_2017-03-24-11-07-53](https://cloud.githubusercontent.com/assets/12967091/24281954/9104cbf0-1082-11e7-977b-f5b045f56118.png)

**Comment by cpg** [comment]
I literally cannot see much of a difference with what is there today. Other than some small font difference (barely noticeable) and the timestamp and size being cut off in half in your third image above (which is unacceptable for the users). So I don't know.

**Comment by nikhilbalyan** [comment]
actually these are the screenshot of the existing application and not of the textview inside the cardview which i was talking about. I will soon send the screenshot of what i intend to implement:D

**Comment by nikhilbalyan** [comment]
@cpg although cardview is part of material design and is a really good feature often used with recyclerview to display list items but they somehow doesn't looks well in our case. here is a screenshot of me implementing the cardview
![screenshot 29 mar 2017 1-02-44 am](https://cloud.githubusercontent.com/assets/12967091/24423753/c374cd1e-141b-11e7-9d57-a4cfb6fe2d64.png)

**Comment by joydeepsaha05** [comment]
@nikhilbalyan I guess we could close this? CardView looks better when there are multiple elements for each item, rather than just a single TextView.

**Comment by nikhilbalyan** [comment]
and moreover when we have a light theme than a card looks nice.
