### ISSUE TITLE
Replace ListViews with RecyclerViews

### ISSUE THREAD

**Issue by adithya321** [amahi/android#147]
Per suggestion from #142 

The RecyclerView widget is a more advanced and flexible version of ListView. This widget is a container for displaying large data sets that can be scrolled very efficiently by maintaining a limited number of views. We must use the RecyclerView when we have data collections whose elements change at runtime based on user action or network events.

Advantages of RecyclerView over ListView
1. Uses ViewHolder pattern to reuse items which improve performance while scrolling
2. ListView can only layout items in a vertical linear arrangement. In contrast, the RecyclerView has a RecyclerView.LayoutManager that allows any item layouts including horizontal lists or staggered grids.
3. Animations for adding and removing items are enabled by default in RecyclerView.

[Using the RecyclerView](https://guides.codepath.com/android/Using-the-RecyclerView)

I'm working on replacing the ListView with RecyclerView in `fragment_server_files.xml`.

**Comment by waadalkatheri** [comment]
i can i replacing the listView with RecyclerView ?

**Comment by adithya321** [comment]
@waadalkatheri I'm working on it and will send a PR soon.

**Comment by waadalkatheri** [comment]
@adithya321 oh ok , but I want ask, how can I fix the issues If the BuildConfig file is Automatically generated file ? 

can you help me

**Comment by adithya321** [comment]
@waadalkatheri I can't understand your question. Please open a separate issue if it is not related to this issue.

**Comment by cpg** [comment]
Can you relate this to the changes in #34 ?

**Comment by adithya321** [comment]
@cpg Yeah. This is similar to that PR but you will be able to tell the difference as I am making some visual changes too.

**Comment by cskc97** [comment]
I'd like to work on this issue!

**Comment by adithya321** [comment]
@cskc97 You can work on it. I got caught up in college work.

**Comment by cskc97** [comment]
@adithya321 Awesome! I'll clone it and work on it. This is a really cool project. I'm gonna be applying through GSoC as well!

**Comment by harshvardhanpro** [comment]
@cskc97 Are you working on this issue ?

**Comment by cskc97** [comment]
@harshvardhanpro yes, I am. I will let you know in the next 36 hours if I get caught up with something else. Is that okay? 
Also, thank you for confirming with me!

**Comment by harshvardhanpro** [comment]
Ya !! go for it. 👍

**Comment by octacode** [comment]
@cskc97 Please let us know about the status of this issue.

**Comment by cskc97** [comment]
@octacode  please go ahead and solve the issue! :)

**Comment by akashagra** [comment]
Can i work on it?

**Comment by octacode** [comment]
Yeah! Sure. 👍

**Comment by akashagra** [comment]
I am not able to login with my username and password , can anyone help me regarding that?

**Comment by shivanshsoni** [comment]
Can I work on this issue??

**Comment by cpg** [comment]
Only the brave will survive issue #147. Pursue your quest to fix #147 with honor, @shivanshsoni.

**Comment by ArihantJain456** [comment]
@shivanshsoni, are you working on this, if not @cpg can I work on this?

**Comment by shivanshsoni** [comment]
@ArihantJain456 Go ahead
