### ISSUE TITLE
Replace Toasts with Snackbars.

### ISSUE THREAD

**Issue by octacode** [amahi/android#148]
#142 

I will replace the given Toasts with Snackbars.

**Comment by nikhilbalyan** [comment]
@octacode please explain the specific places where you want to replace Toasts with Snackbars because both of them have their own use cases you can't just randomly go and replace all Toasts with snackbars

**Comment by ak2711** [comment]
can i work on this issue?

**Comment by cpg** [comment]
@ak2711 please let @octacode confirm he's working on it.

**Comment by ak2711** [comment]
Are there any issues that are not assigned

**Comment by cpg** [comment]
You can go through the issues and see if someone said they will work on it. You could also simply add new features you would like to see in the app after using it. Or make fixes/improvements that are sensible to you.

**Comment by octacode** [comment]
Sorry I got up in submissions will update you all with the PR status very soon.

**Comment by octacode** [comment]
**Settings Fragment**:-
While Signing out - Toast is fine as there's an activity change and we want to display the message over the change which isn't possible with Snackbars because Snackbar's instance dies with the activity which isn't the case with Toast.
In setUpApplicationFeedback() and setUpApplicationRating() :- Snackbar will look awesome. :)
**ServerFilesFragment**:- Here replacing Toasts with Snackbars isn't going to do us any harm.
**GooglePlaySearchFragment**:-Here too we can replace the Toasts with Snackbars.

Thanks
