### ISSUE TITLE
Automatically generated file. DO NOT MODIFY

### ISSUE THREAD

**Issue by waadalkatheri** [amahi/android#150]
I want fix some issues but I can't edit the file BuildConfig because is  Automatically generated file 
how can fix issues  if the file is Automatically generated file ?

**Comment by nikhilbalyan** [comment]
It is irony but @waadalkatheri you don't need to modify buildconfig file

**Comment by adithya321** [comment]
You cannot edit `BuilConfig.java`. Set API information by creating a `api.properties` file as given in README.
