### ISSUE TITLE
Replacing deprecated RemoteControlClient with MediaSession's Media Controls 

### ISSUE THREAD

**Issue by csoni111** [amahi/android#155]
In the [AudioService.java](https://github.com/amahi/android/blob/master/src/main/java/org/amahi/anywhere/service/AudioService.java#L89) we are using the old and deprecated `RemoteControlClient` _( deprecated since api 21 or android 5.0)_ to play the music in background service. 
This needs to be replaced by `MediaSessionCompat`.
You may check the changes here on [developer.android.com](https://developer.android.com/about/versions/android-5.0-changes.html#BehaviorMediaControl).

The replacement will offer greater control on the music player and allow music controls to be shown on LockScreen. I shall be working on this issue over the next week.

**Comment by anujgupta61** [comment]
If no-one is working on this issue , can I work on it ?

**Comment by csoni111** [comment]
@anujgupta61 I am working on the issue.

**Comment by anujgupta61** [comment]
Okay .
