### ISSUE TITLE
Reformat Code

### ISSUE THREAD

**Issue by adithya321** [amahi/android#158]
I am used to reformatting code (Cmd+Alt+L in mac) and I have to undo that everytime as it changes a lot in every file. For example, PR #108 and #157. 

I use the Default code style scheme in Android Studio but we can use any code style by committing `.idea/codeStyleSettings.xml`. By doing this everyone can reformat code to match the style before committing. 

@cpg How do you think we can reformat the whole codebase?

**Comment by guenodz** [comment]
Personally I use the official Google code style for Android projects [here](https://github.com/android/platform_development/blob/master/ide/intellij/codestyles/AndroidStyle.xml). We can use it or use another common style, or we can use the default code style in IntellijIdea. What do you think ?

**Comment by cpg** [comment]
We discussed about this and agreed to adopt this. The only remaining thing is to add a section (before the `Generating the documentation` section) in the README titled `Code Style Convention` with details for other developers to follow when thy contribute in the future.

After you do that (separate PR) we can close this. Thanks!

**Comment by adithya321** [comment]
I am working on it and I will send a PR soon.
