### ISSUE TITLE
Use ExoPlayer in place of MediaPlayer(MediaController)

### ISSUE THREAD

**Issue by harshvardhanpro** [amahi/android#165]
About Exoplayer :
The Android framework provides MediaPlayer as a quick solution for playing media with minimal code, and the MediaCodec and MediaExtractor classes are provided for building custom media players. ExoPlayer is an open source project that provides a solution falling somewhere between these two options. It is a player that you can modify and extend.
 Also it includes tunneled video playback.
Primarily intended for Android TVs, tunneled video playback promises benefits such as better audio/video synchronization (AV sync) and smoother playback. 
https://developer.android.com/guide/topics/media/exoplayer.html

**Comment by harshvardhanpro** [comment]
I think its implementation will take a lot of time. So, I think I will add it in secondary idea in my proposal.
Can someone suggest, what i am thinking is right or wrong?

**Comment by cpg** [comment]
It took us a long time to get to where we are, so I am not too inclined to just switch, given that what we have is not bad and it works for basically most/all media I have been throwing at it.

**Comment by harshvardhanpro** [comment]
@cpg I know its working fine now, but in near future when you will add more fetures to it, it will become more difficult to understand the code and more and more issues will rise.
i may not be the expert, you can consult with @megabitdragon or @bigfoot65 on the issue...

**Comment by ArihantJain456** [comment]
@cpg I would like to work on this issue.
Also since my last PR #331, I'm very much familiar with the `audioService` and `MediaPlayer` implementation code and will be able to finish it very soon. And also I have done a simple implementation of ExoPlayer before.

**Comment by cpg** [comment]
Just to be clear --

1) This will be for audio-only, no video at all
2) Will not break Chromecast casting -- what is tunneled video?
3) Will provide extra advantages vs what we have -- what are those?
