### ISSUE TITLE
advice from the Android developers blog related to aspect ratios

### ISSUE THREAD

**Issue by cpg** [amahi/android#177]
The Google Play console advises that Amahi for Android [may need to be updated to handle newer aspect ratios](https://android-developers.googleblog.com/2017/03/update-your-app-to-take-advantage-of.html).

Seems like a simple change from a cursory reading. Not sure this is something we need yet or if it has potential negatives.

**Comment by octacode** [comment]
@cpg....It's not a big issue. I'll fix it.
