### ISSUE TITLE
accent colour not following material design guidelines

### ISSUE THREAD

**Issue by doomers** [amahi/android#179]
after #175 ,with the addition of primary and accent color, app is looking nicer than before
but if we go by material design guidelines accent color should be a light colour of 200
https://material.io/guidelines/style/color.html#color-color-palette

but we are using orange of value 500, which looks quite  odd, 
and also as our app has a dark theme, we can use orange colour of value 300 also and it is also looking nicer than the 200 one.

**Comment by cpg** [comment]
done
