### ISSUE TITLE
Adding toast message showing press back again to exit 

### ISSUE THREAD

**Issue by rdeveloperIITR** [amahi/android#184]
**Summary:**

Adding Toast message to click back again to exit

**Steps to reproduce:**

Click the physical back button(it directly closes the application)

**Expected behavior:**

Toast message saying that "press back again to exit"  is shown and if within a certain time interval back
is pressed again then close the application.

**Observed behavior:**

Application is closed directly

**Screenshots:**

![screenshot_2017-04-02-02-10-34](https://cloud.githubusercontent.com/assets/24658811/24582282/b8b5fe8a-1749-11e7-8939-c6fb50b00abc.png)

**Comment by rdeveloperIITR** [comment]
I would like to work on this :)

**Comment by octacode** [comment]
@rdeveloperIITR ...this issue has already been raised and considered unnecessary. Please refer #118.
Can close this one.
