### ISSUE TITLE
Prepare the app for android O

### ISSUE THREAD

**Issue by megabitdragon** [amahi/android#188]
[Here](https://developer.android.com/preview/index.html) is the guide for reference.

**Comment by octacode** [comment]
I tested our App by flashing the Android O disc image on a Nexus 5 and Pixel emulator and it worked great! and in the docs it's mentioned that we don't need to update the libraries for compiling so there's nothing which should be done here. For testing I used Android Studio's canary version.

**Comment by cpg** [comment]
all working. yay!
