### ISSUE TITLE
some photos cannot be opened by the app!

### ISSUE THREAD

**Issue by cpg** [amahi/android#189]
I noticed this in some browsing through early on but I attributed to some weirdness of my setup.

Looks like a bug. Others are also [having trouble opening some images](http://rickwright.co.nz/amahi/amahi.htm)!

**Comment by Rickwright12** [comment]
let me know if you want more detail on it.

**Comment by csoni111** [comment]
Looks like that's a bug in the Picasso library itself. I have opened an [issue](https://github.com/square/picasso/issues/1613) on the picasso's github repository.
Let's see if someone responds there. 

In the meantime, I have tried loading the same image using other image loading libraries (like [UniversalImageLoader](https://github.com/nostra13/Android-Universal-Image-Loader) and [Glide](https://github.com/bumptech/glide)) and it seems to load perfectly fine using these.

If we want a quick resolution we may switch to these other open source libraries.!

**Comment by cpg** [comment]
Now, is this a light change (like a few lines) that is mostly all compatible? Or is it a change that requires adjusting a bunch of code and has behavioral changes?

One thing is that picasso seems slow in responding to issues and fixing things.

The other thing is that it's surprising that many people did not notice this issue in that library. Is it not widely used?

**Comment by Rickwright12** [comment]
just trawling thru the picasso errors...  found similar one.  https://github.com/square/picasso/issues/1514  
I have tried the two photos referenced in their error,  first one will not load, the second one does.  downloaded android studio to see if I could muck around and learn anything.  more confused than anything. check above error, re resize() which is what I was trying to look at.

**Comment by cpg** [comment]
Great job! Tested it, merged it and released it as version 2.2. Look for it in the play store!
