### ISSUE TITLE
Enhancement: Password field visibility

### ISSUE THREAD

**Issue by top-gun007** [amahi/android#19]
**Summary**:
There should be a button to view typed in password just like in all popular apps.

**Screenshot:**
![image](https://cloud.githubusercontent.com/assets/15179401/23587193/05648784-01cd-11e7-8186-5a2611d0ab12.png)

**Comment by asifali1234** [comment]
Hi all,
I would like to contribute to the Amahi Android app. I will try fixing this issue.

**Comment by DoMINAToR98** [comment]
Can i fix this?

**Comment by top-gun007** [comment]
I have assigned this to myself
Thank you

Get Outlook for Android<https://aka.ms/ghei36>



On Mon, Mar 6, 2017 at 3:24 AM +0530, "Kartik Sharma" <notifications@github.com<mailto:notifications@github.com>> wrote:


Can i fix this?

**Comment by mehtamanan0** [comment]
This Feature is addded in the PR  #20 . @top-gun007 @asifali1234 @DoMINAToR98 Feel free to add any more functionality into the login screen as you may like , try to come up with Innovative ways to make the login Screen more Creative.

**Comment by lakshyagupta21** [comment]
Is there any progress on this issue. If nobody is working on it then can i work on this ?

**Comment by Ishmeetsingh97** [comment]
Hi, is there any developments on this ? I would like to work on it.
