### ISSUE TITLE
Music player controls are not visible

### ISSUE THREAD

**Issue by megabitdragon** [amahi/android#191]
The music player controls are not visible on the lock screen or from the notification bar. The device is running Android 7.1.1
![screenshot_20170410-085012](https://cloud.githubusercontent.com/assets/2903227/24864902/3b8509a0-1dcb-11e7-8c3d-dcfa9e5228d5.png)
![screenshot_20170410-084955](https://cloud.githubusercontent.com/assets/2903227/24864906/3ee6492e-1dcb-11e7-8ed1-0043b242f3b2.png)

**Comment by csoni111** [comment]
My bad! I did not test it on android 7. Will resolve it soon.
