### ISSUE TITLE
Updating and displaying the percentage of buffering while opening a video

### ISSUE THREAD

**Issue by octacode** [amahi/android#208]
This'll make Amahi more transparent and user friendly.

**Comment by csoni111** [comment]
This feature has already been listed out in an issue (#76) and I had implemented this a month ago _(check this [commit](https://github.com/csoni111/amahi-android/commit/23376fa1a1da4ffa83d812c7d29df1d0464aaebf))_, but I thought it would be better to make all the updates as mentioned in that issue and then open a single pr.

**Comment by octacode** [comment]
Okay! If you need any help then please feel free to ask as I've worked on a Video Playing app before. :)
