### ISSUE TITLE
Keyboard covering Up TextFields

### ISSUE THREAD

**Issue by mehtamanan0** [amahi/android#21]
as @cpg mentioned there is a problem in some phones where the keyboard covers up the textfields , So what @cpg suggested was to move the logo down below like:

![screenshot 06-mar-2017 2_26_02 am](https://cloud.githubusercontent.com/assets/16348397/23591384/5803e484-01e7-11e7-8519-bbc320ceee2a.png)

What would you all suggest?

**Comment by PiyushGupta007** [comment]
Can I work on it ?

**Comment by mehtamanan0** [comment]
@PiyushGupta007  yes sure go ahead

**Comment by lakshyagupta21** [comment]
Is it really necessary to change position of logo to just make textfield visible. Logo is always preferable at the top. The same thing can happen in some devices if you change orientation of your screen from portrait to landscape. To solve this issue what we can do move our layout  up whenver soft keyboard opens up. As our main priority is to write in textfield whenever softkeyboard opens up so other fields and images are not necessary to be visible at that time. Visible i mean if screen is small then we can't afford to make all component visible in that size of screen. Correct me if i am wrong anywhere.

**Comment by csoni111** [comment]
I agree with @lakshyagupta21, moving the logo down is a bad idea!
As @mehtamanan0 suggested in [#20](https://github.com/amahi/android/pull/20#issuecomment-284251988), we can use `WindowSoftInputmode` in the manifest to move the layout up on opening the soft keyboard. That way the text fields will always be visible.

**Comment by PiyushGupta007** [comment]
On it

**Comment by cpg** [comment]
It's not just the text that needs to be visible, but the Sign In button as well, to avoid having to close the keyboard to be able to click it.

**Comment by lakshyagupta21** [comment]
We can add event listener for enter key of soft keyboard which will move you to the "password" field if you are writing on "username" field and for "password" field enter key will directly call the login method. I don't think that we can afford to have two components (one EditText and Sign In Button) and also a soft keyboard at a time all together in devices with small screen size. Correct me if i am wrong.

**Comment by octacode** [comment]
@lakshyagupta21 android handles this on its own. We just have to set softInputMode attribute in the manifest file as true.

**Comment by pranavgupta1234** [comment]
Any updates on this ? I would like to resolve it :)

**Comment by cpg** [comment]
I believe @PiyushGupta007 was working on this issue. Perhaps he can chime in with the status.

**Comment by asifali1234** [comment]
@lakshyagupta21  I think sign in button is needed in the app. It would create unnecessary ambiguity if there is no sign in button
I think we could implement the idea as suggested by @csoni111

**Comment by lakshyagupta21** [comment]
@asifali1234 I think you misunderstood my comment , I didn't mean anything about removing signUp button i said that we can't afford to have 2-3 components and softKeyboard visibility on a screen altogether. 
Yes it is also possible for the devices which have bigger screen sizes. And definitely it will create ambiguity if we remove signup button, which is not the case. There must be a signup button but it may be hidden behind soft Keyboard when you scroll other components up then it will definitely come up.

**Comment by lakshyagupta21** [comment]
@asifali1234 And to implement above thing we have to definitely use the idea that @csoni111 suggested. Without that it would be difficult to implement above functionality.

**Comment by hshrimali** [comment]
If no one is sending PR, then can I? I'm already done with this feature as per your requirements, just need to click that PR tab .

**Comment by PiyushGupta007** [comment]
@hshrimali  @cpg  sorry i was sick for day and a half , @hshrimali  go for it  .
 also need url.amahi , url.proxy  , client.id etc ( url illegal error ) .

**Comment by hshrimali** [comment]
Okay, Thanks @PiyushGupta007

**Comment by hshrimali** [comment]
@cpg  I'm done with the solution of this issue. I have sent the PR. You can refer PR #50 .

**Comment by cpg** [comment]
In the current PR #50 I still do not see the sign in button, so it feels weird to have to remove the keyboard.

This is turning out quite a thing, when in reality is simple.

Could you guys look at mainstream apps and try something sensible?

Skype (they move the logo and the fields up top of the screen), Facebook Messenger (they slide the whole page up to the point the logo is not visible any more), Snapchat (has no logo and has all fields up top), Instagram (not so good, they move fields up, but still some overlap with the "Next" field). ...

Could you try some of the most popular apps that require login and check their login form implementation?

**Comment by hshrimali** [comment]
@cpg Taking your idea into consideration. Now, I have implemented it in such a way that whenever user wants to enter something in username or password the Amahi icon disappear and only the EditTexts and the Sign In button appears and after completing the information when user clicks the button, the Amahi icon reappears with all other information.

Below picture is during editing the text

![screenshot_20170316-023726](https://cloud.githubusercontent.com/assets/17125712/23970973/f3784894-09f1-11e7-924d-7d113538ead3.jpg)


Below picture is after hitting the Sign In button

![screenshot_20170316-023752](https://cloud.githubusercontent.com/assets/17125712/23971071/63e49cb8-09f2-11e7-8f4e-c01b9e1f7f4d.jpg)

@cpg Now, if it looks good to you, I can make the pull request.

**Comment by cpg** [comment]
This is not a "look" thing but a "feel" and UI think, so without a PR to test it out, I feel I cannot comment much.

**Comment by hshrimali** [comment]
Okay @cpg  I'm sending a new PR.

**Comment by hshrimali** [comment]
@cpg I have sent the PR you can check it. Thanks.
