### ISSUE TITLE
How to handle Amahi for Android TV code, app, etc.

### ISSUE THREAD

**Issue by octacode** [amahi/android#213]
The question is do we need a separate app for Android TV or is it fine to create a new module for it in the present app itself.

**Comment by batbrain7** [comment]
I suggest that if we will have a new app then we should make a separate repository for it

**Comment by octacode** [comment]
@batbrain7 separate repository is not an issue. It's just whether the changes will complicate the code.

**Comment by octacode** [comment]
Personally I don't think it will complicate the code. For the time being we can actually create a new branch and make the changes there and later on merge it with the main branch. Moreover a separate repository will mean 2 different apps on playstore which we obviously don't want.

**Comment by cpg** [comment]
I will agree that two separate apps is not something we want, if we can avoid it, but it's not catastrophic if we have to.

For me, the question is managing the code changes for Android TV and how they can interfere with the main app.

Will we need a method IsAndroidTV()?

Will we need to use it often and sprinkle the code everywhere with it?

Will layout files and events be handled significantly different than for the main app (which up to now we have focused for phones/tablets)?

If these are not significant issues, we would prefer to keep things in one app.

**Comment by octacode** [comment]
No the code changes will not interfere with the main app. TV layouts, it's Java code and it's libraries will be handled separately. So these issues aren't really significant. We should keep things in one app.

**Comment by cpg** [comment]
Ok, I hope we can keep it all in one app and one code base, under the assumption it does not create a significant hindrance for the main app.

We have created a branch for it called `android-tv`. Let's issue PRs against it in the future then one day test with a merge.
