### ISSUE TITLE
Duplication of code between ATV and the "master" app

### ISSUE THREAD

**Issue by octacode** [amahi/android#218]
Basically we need to find a work around to keep some things between the two modules(ATV & "master") like the API requests. So that if somethings are changed in the future we don't have to change them at two places.

**Comment by octacode** [comment]
This has been resolved.

**Comment by octacode** [comment]
Earlier I was creating a new module for android-tv where the previous code was just copied and integrated with the TV layouts which I've created already.

Now I have used a function isATV(); which tells whether the app is run in android TV or not. If the device is an android TV then the shares, apps and servers are fetched first with the progress bar being displayed. Once the networking call are made then the Shares, Apps and Servers fetched are passed as `parcelableExtra()` to an Intent which actually is our MainActivity for Android TV.

**Comment by cpg** [comment]
this has been merged into a single codebase without much duplication
