### ISSUE TITLE
the movie files inside the movie share should display the metadata artwork in ATV

### ISSUE THREAD

**Issue by cpg** [amahi/android#236]
the movie files inside the movie share should display the metadata artwork in ATV, just like in the phone side (so please check the code on that side to see how metadata is used).

**Comment by cpg** [comment]
So, I think some of this was not done as in the phone side:
- folders are looked up for metadata (they shouldn't), resulting in weird movies sometimes (e.g. if I have alphabetical folders)
- files inside of folders (or inside folders of folders) are not looked up for metadata

I'm pretty sure the phone code does both of the above properly.

**Comment by octacode** [comment]
PR #238 ffixes this.
