### ISSUE TITLE
ATV usability: on-screen controls are very hard to use

### ISSUE THREAD

**Issue by cpg** [amahi/android#248]
1) the screen should not grey-out when a movie is playing and the controls come up. this is quite annoying, because it hinders watching the movie while it plays.

2) i would even suggest moving the controls lower to the bottom of the screen as they are very intrusive.

3) the next and previous buttons are not really necessary when playing movies. they may be while playing audio, however. can we just put "fast fast-foward" buttons instead to move faster in the movie when not playing audio?

4) in the hand controller, other apps allow me to move left and right to scrobble the movie. here, i have to click right, then press a button (and holding it does not repeat!!) to scrobble forward. the controller has two joysticks and lots of buttons that could be used to do this better. can we do something like what others do (e.g. kodi)?

**Comment by cpg** [comment]
example from the [kodi ui](https://www.dropbox.com/s/4nnntnlzpqsmfwo/Screen%20Shot%202017-07-22%20at%208.49.14%20PM.png?dl=0)

**Comment by octacode** [comment]
1. We can remove the screen greying out. :+1: 
2. We're using the `playbackOverlay` fragment. And the controller is by default. YouTube also uses the same.
![youtube](https://user-images.githubusercontent.com/20819968/28497070-996965a4-6f9a-11e7-90b6-648cb8b0e394.png)
3. We can remove the `skipNext` and `skipPrevvious` buttons for movies and if It's a movie do we even need to show the other movies are in the folder in the bottom row of the video player? But say If I have a folder *not in movies share* which consists of some music videos then we may want these buttons and auto-play next when the video completes. Another option can be we remove these two buttons for all type of Videos?
4. I checked out [Kodi](https://github.com/xbmc/android/tree/android-rebase-11/xbmc/video) and switching to a new video player will be a lot of work. Can we mark this as low priority and come to this once we're done with the `non-admin users`.

**Comment by cpg** [comment]
resolved and merged onto `beta` branch
