### ISSUE TITLE
ATV usability: too easy to exit the app

### ISSUE THREAD

**Issue by cpg** [amahi/android#249]
i notice i have to use too much thinking to use the app or i easily exit it, then i have to find it again to use it, navigate to my folders, etc.

other apps require clicking on a "power" button (with a power icon) with an exit confirmation, to exit the app. clicking on exit takes you back to the UI and exit again back to reproduction of the movie. can we do something similar?

**Comment by octacode** [comment]
Thanks for pointing out. We should do it the way the other apps do. :+1:

**Comment by cpg** [comment]
resolved and merged!
