### ISSUE TITLE
port app to android 7

### ISSUE THREAD

**Issue by cpg** [amahi/android#26]
update app to work well in android 7

[bug 2127](https://bugs.amahi.org/issues/2127)

**Comment by mehtamanan0** [comment]
@cpg i did put in a pull request for adding that.

**Comment by cpg** [comment]
it was done in #10. my bad.

**Comment by megabitdragon** [comment]
This bug is too broad. Updating the sdk is not  a port to Android 7. There are a lot of things that are broken and others that need testing. Please leave the bug open. I'll add specifics as new issues and we'll close this when we have a fully functional app on sdk 25.

**Comment by anand9522** [comment]
Can I work on it? Please confirm.

**Comment by megabitdragon** [comment]
@anand9522 Please read my comment above. Pick **specific** issues for the tracker or build the app and see what you can change/improve. We will add more specific issues in the next few days.

**Comment by cpg** [comment]
things work on android 7. thanks @octacode
