### ISSUE TITLE
Overwrite a file if it already exists in the storage

### ISSUE THREAD

**Issue by octacode** [amahi/android#276]
One of the Amahi users reported the following: 
1. > Hello, I would really like an option to overwrite files or to append (-1, -2... Etc). Anytime I go for an updated version of my file, it's just going to save a while new copy. Then I'm going to have to do house keeping or else my phone storage will get full in a month.
2. > That's pretty cool! I, however, may have been unclear in my request: when I download a file to my phone, I would like the option to overwrite an existing copy of that file rather than the app appending the fresh copy with a "-1".

### ISSUE
Currently when the user tries to share a file, first the file gets downloaded and then the downloaded file is shared via sharedIntent. This file downloaded is stored in `Android/data/org.amahi.anywhere/downloads` and if the user tries to share the same file again and again then multiple copies of the file will be created in the storage. 

### SUGGESTED SOLUTION
So **before triggering** any new download we'll look for the file with the same name and the same mime type in the path mentioned above. If the file exists then we will delete it and then download the file. Hence overwriting it. The user will not the prompted when overwrite takes place.

**Comment by rizal-rovins** [comment]
Can you point out the activity where this is to be implemented?

**Comment by csoni111** [comment]
@rizal-rovins you can look into the code here in [util/Downloader.java](https://github.com/amahi/android/blob/8b8764d4863ba3b0e750b5d6abe2397be2735be5/src/main/java/org/amahi/anywhere/util/Downloader.java#L58)

**Comment by sd1998** [comment]
@octacode  I would like to work on this issue

**Comment by csoni111** [comment]
#277 resolves this
