### ISSUE TITLE
No signup option in the app

### ISSUE THREAD

**Issue by akashagra** [amahi/android#283]
It would be great if we work on creating a sign up option for the new users.
I can help in creating the UI and the server side work can be done by someone else

**Comment by cpg** [comment]
Amahi is a home server. Without a server, there is no use for the mobile apps, however. We would get a lot of frustrated new users that would not have a server and would be frustrated. Until we have some sort of public sharing, this is not too useful. Thanks for the idea. Maybe we will need this one day, but not yet.
