### ISSUE TITLE
Casting video to Chromecast fails to play audio

### ISSUE THREAD

**Issue by rbmattis** [amahi/android#287]
Most video files successfully stream to Chromecast from HDA via Amahi App; however, 1080p matroska h264 video, DTS 7-channel audio outputs no sound. File plays successfully on all other players

**Comment by rbmattis** [comment]
I just confirmed that the audio doesn't work in the Amahi App itself, either. Same file: 1080p matroska h264 video, DTS 7-channel audio

**Comment by cpg** [comment]
Ok, that helps.

I think it may be a non-supported audio stream for the built-in audio/video stack.

We don't have a setting to "play using alternative player" at the moment (maybe we should?). THe alternative player is based on the same library that VLC uses, which may work, however, it may not cast to Chromecast.

**Comment by csoni111** [comment]
@rbmattis It would be helpful if you could upload a sample video in that format so that it can be tested _(somewhere in the cloud like on Google Drive)_.

**Comment by rbmattis** [comment]
How can I trim a 14 gig file to a five meg clip, easily?

**Comment by rbmattis** [comment]
https://drive.google.com/open?id=1Bh00aP6i96-1bWmy_1Ujbh56Mtps1eYw

**Comment by rbmattis** [comment]
was that helpful?

**Comment by csoni111** [comment]
Yes it was helpful indeed! I tried to play the file, it does not play audio in the android's default media player but it plays fine in libvlc player _(we can have an option to play the file using alternate player as @cpg suggested)_.
As for the chromecast support, the [officials docs](https://developers.google.com/cast/docs/media) says that it supports only following audio codecs: 

**Audio codecs**
- HE-AAC
- LC-AAC
- MP3
- Vorbis
- WAV (LPCM)
- FLAC
- Opus

Unfortunately DTS audio codec is not supported at the moment.
