### ISSUE TITLE
trouble opening PDF files

### ISSUE THREAD

**Issue by cpg** [amahi/android#290]
user reporting in ..

> Using Samsung Galaxy S7 Android phone.
> Amahi for Android app displays all files and plays mp3s but will not open text files such as PDF. I do have Adobe on my phone. The app reports it downloads the file but then reports it cannot be accessed, check network or location.
> This happens whether connecting via LAN or remotely.

**Comment by cpg** [comment]
Verified with three PDF apps that the file appears to be downloaded in the client (there is a message saying so) as well as in the server (there is one call and the number of bytes sent are the exact size of the PDF file).

The Amahi app asks what app to use to open the file and then it fails. Including a Google an and Adobe PDF reader, as well as one with very high rating called "2018 PDF Reader".

**Comment by santosh62** [comment]
did you used any `PDF reader` library??

**Comment by octacode** [comment]
The same happens with other file formats like `.docx` `.pptx` `xls` `.txt` etc. One thing to notice is that the share feature is not broken, it downloads the file and then shares the downloaded file

**Comment by ArihantJain456** [comment]
I'm working on this issue.

**Comment by ArihantJain456** [comment]
@cpg I'm facing problem in setting DNS for my amahi server.
I have followed this article [https://viky.co.in/2017/05/20/install-amahi-server-for-development/](https://viky.co.in/2017/05/20/install-amahi-server-for-development/)
My server is running but I'm not able to access `hda/`

**Comment by ArihantJain456** [comment]
I am solving some other issue now. I will come to this issue after successful development of my server.
