### ISSUE TITLE
How to bypass Log In page of Amahi App

### ISSUE THREAD

**Issue by pprathameshmore** [amahi/android#291]
I am student. I want to contribute for this project as GSoC.
I new to open source. I already cloned repo of Amahi Android app.
I want bypass log in page to test app.
Please help me

**Comment by octacode** [comment]
Hi! You'll be requiring the credentials which are required to build the app successfully. However these credentials are not to be meant to be shared publicly. Ask for the credentials in the IRC. Closing this for now.

**Comment by csoni111** [comment]
You do not need to bypass the login page, you can login with credentials same as for amahi.org
If you do not have an account, you may register [here](https://www.amahi.org/signup).

**Comment by cpg** [comment]
Both comments above are correct. You need a an api properties file (email support at amahi and we'll send you the details). You also need to be logged in with amahi.org credentials.
