### ISSUE TITLE
Getting Introduction Activity on pressing back button

### ISSUE THREAD

**Issue by adi23arora** [amahi/android#292]
Introduction Activity is not being shown on the first launch when the user is not logged in. It gets added to Back Stack and is replaced by Authentication Activity.

Can anyone confirm that this is a bug or done intentionally?

**Comment by octacode** [comment]
I did it intentionally thinking this flow to be right

**Comment by adi23arora** [comment]
Getting Introduction Activity on pressing Back button is also intentional?

**Comment by octacode** [comment]
Okay! I did a quick check and yes I think getting the Introduction Activity by pressing the back button definitely is a bug. Thanks for pointing it out. Will you work on this?

**Comment by adi23arora** [comment]
Yes, I want to work on this.

**Comment by adi23arora** [comment]
@octacode Please review the PR.
