### ISSUE TITLE
No way to see introduction screen again

### ISSUE THREAD

**Issue by mohitsvnit** [amahi/android#294]
Introductory screens are shown only when user opens app for the first time.
It may happen that user will skip them and would like to see them afterwards.
But there is no way in app to see them again.

**Comment by mohitsvnit** [comment]
I would like to work on it.
Where should I place a button for it?

**Comment by cpg** [comment]
Settings area?

**Comment by mohitsvnit** [comment]
ok. will do that.

**Comment by cpg** [comment]
Suggested text: "Intro"

**Comment by mohitsvnit** [comment]
Inside about section right?
