### ISSUE TITLE
Items on share screen doesn't show any pressing effect

### ISSUE THREAD

**Issue by mohitsvnit** [amahi/android#296]
Items on below screen like "Demo" doesn't show any pressing effect on pressing.

![screenshot_2018-03-01-19-23-12](https://user-images.githubusercontent.com/12980721/36848225-a4c825b2-1d86-11e8-834a-fa40294fe993.png)

**Comment by csoni111** [comment]
I tried, it seems to show the ripple effect on press.
![demo screen](https://i.imgur.com/IPDKK6t.jpg)

**Comment by mohitsvnit** [comment]
I am building beta branch app.
My OS: Android 5.1

![screenshot_2018-03-01-19-37-34](https://user-images.githubusercontent.com/12980721/36848824-64f80c20-1d88-11e8-968f-a07741ddea4c.png)

**Comment by adi23arora** [comment]
@mohitsvnit, I too can see the ripple effect. I guess this ripple effect works only on API 21 onwards.

**Comment by mohitsvnit** [comment]
My os version is 5.1 so its api level is 22

**Comment by mohitsvnit** [comment]
I solved the this issue. Should I commit change?

![screenshot_2018-03-01-21-55-00](https://user-images.githubusercontent.com/12980721/36856215-7605166c-1d9b-11e8-85cc-3518bd2f7e0e.png)

**Comment by csoni111** [comment]
Closed via #305
