### ISSUE TITLE
Issues with the Android-tv and Chromecast Ids

### ISSUE THREAD

**Issue by octacode** [amahi/android#298]
There have been some unresolved last moment issues with the android-tv ID and chromecast ID which occured during publishing the Android app on play store.

**Comment by cpg** [comment]
I screwed this one up and I need to re-generate the cast app details. I think it was a **Styled Media Receiver**?

Could someone guide me please:

```
New Receiver Application
Please select the type of application you would like to create:

Custom Receiver
Receiver app you can build using the Cast Receiver SDK and host yourself.

Styled Media Receiver
Pre-built receiver app that you can style using CSS. No need to build or host.

Remote Display Receiver
Receiver app that you can use with Cast Remote Display sender applications.
```

**Comment by csoni111** [comment]
yes we have **Styled Media Receiver** with support files listed [here](https://github.com/amahi/android/tree/master/cast).
