### ISSUE TITLE
No link for faq of amahi in app

### ISSUE THREAD

**Issue by mohitsvnit** [amahi/android#299]
To see the faq for amahi user needs to open website.
There is no direct link to faq inside app.

**Comment by mohitsvnit** [comment]
I would like to work on it.

**Comment by adi23arora** [comment]
How you are planning to implement this?

**Comment by mohitsvnit** [comment]
By adding link to faq present on amahi website.

**Comment by octacode** [comment]
Maybe we can add a listItem reading "FAQs" which redirects to the Amahi FAQ website. However do we really need to do this? I guess it's a matter of personal preference. @cpg your views on this?

**Comment by mohitsvnit** [comment]
@octacode I was thinking same. There is not faq in about section of app.

**Comment by cpg** [comment]
No please. This is fluff and unnecessary for users of the app.
