### ISSUE TITLE
Replacing the png drawables by their vector counterparts

### ISSUE THREAD

**Issue by lakshyagupta21** [amahi/android#30]
Currently we have png drawables for everything like back button, menu and other icons. Replacing png drawables with their vector counterpart which will be a one XML file for five drawables will definitely going to reduce APK size. Vector drawables also scale very well. PNG is a compressed image trying to make it bigger or smaller will make image doesn't look right.

**Comment by csoni111** [comment]
I think that is a nice idea!

These two sites will help:
[Material icons](https://material.io/icons/)
[svg to vector drawables](http://inloop.github.io/svg2android/)

**Comment by yashsharan** [comment]
Can i work on it?

**Comment by cpg** [comment]
@yashsharan If you think this is something up your alley, sure. However, I am not sure if @lakshyagupta21 (or others) were planning to work on it.

**Comment by lakshyagupta21** [comment]
@yashsharan if you really want to work then please go ahead !!

**Comment by lakshyagupta21** [comment]
@yashsharan Any updates on this issue ? If you are not working then i would like to work on this issue.

**Comment by doomers** [comment]
@lakshyagupta21 @yashsharan @cpg 
If no one is working on it? I would like to work on it

**Comment by cpg** [comment]
@doomers : since @lakshyagupta21 is the original person suggesting this and he's willing to do it above, I think he should. If he does not respond in 24 hours, I would say you reply here and get started.

**Comment by doomers** [comment]
@cpg okay.

**Comment by lakshyagupta21** [comment]
@cpg Thanks for giving me this issue. I am on it.

**Comment by lakshyagupta21** [comment]
@doomers If you want to work on it go ahead , i am not getting enough time these days so will not be able to do.

**Comment by doomers** [comment]
Okay @lakshyagupta21 I am taking up this issue.

**Comment by adithya321** [comment]
There are five more PNG drawables which can be converted to SVG. 
```
ic_menu_settings.png
ic_menu_sort_modification_time.png
ic_menu_sort_name.png
ic_notification_audio.png
ic_file_audio.png
```
These are not standard Material icons. I can replace them with their Material equivalents.
@cpg Should I?
