### ISSUE TITLE
Replacing deprecated dependency configuration methods

### ISSUE THREAD

**Issue by adi23arora** [amahi/android#304]
The methods used in build.gradle to handle various dependencies like `compile`
are now deprecated and its replacement `implementation` has various optimizations like
less exposing classpaths and faster compilations.

Here's a link to the gradle docs with detailed explanation : [Gradle Docs](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation)

**Comment by adi23arora** [comment]
@csoni111 Should I proceed with a PR on the same?

**Comment by cpg** [comment]
If it's not a lot of work (as I would suspect), let's see it.

**Comment by adi23arora** [comment]
@cpg It just involves replacing the keywords in `build.gradle` file.
