### ISSUE TITLE
Interceptor can expose API info in endpoints

### ISSUE THREAD

**Issue by adi23arora** [amahi/android#306]
In recent commits, interceptors were added. But these should be restricted in production builds because these may leak the API info like access tokens and session ids in GET urls and response headers.

There was a workaround for `chuck` interceptor to deal with release builds using the `library-no-op` but there's no check on the `HttpLoggingInterceptor` which is used at `Level.HEADERS`, at this level details like the end-point urls and response headers are exposed.

![exposing-get-url](https://user-images.githubusercontent.com/17095968/36939985-dcef68b6-1f60-11e8-800e-aa5882056853.jpg)

This image shows an example of some private info that can be leaked in an endpoint url.

**Comment by cpg** [comment]
See [this question an explanation](https://github.com/amahi/android/pull/288#issuecomment-370144935)

**Comment by adi23arora** [comment]
@cpg I already saw that and that's what I have mentioned that `chuck` interceptor is already dealt with using that `library-no-op` but the other there should be a check on `HttpLoggingInterceptor` too.

**Comment by adi23arora** [comment]
1. No, it's not a part of 'chuck'. Using `HttpLoggingInterceptor` we can see logs on Android Monitor or Logcat, while `chuck` enables us to see on the Android device itself.
2. Yes, its needed to monitor or debug api using Android Studio itself.
3. General users won't be able to see but any advance user can try to peek into the logs our app is creating and in this way, some api related info can be exposed.

**Comment by csoni111** [comment]
@cpg: Yes, @adi23arora is correct. `HttpLoggingInterceptor` is not the part of chuck. It has been in the app since start. Although normal users won't see the logs but an advanced user can.

@adi23arora you may add a if condition [here ](https://github.com/amahi/android/blob/2c1a1a55aee94d1a78bd474368f314fe9bcd4045/src/main/java/org/amahi/anywhere/server/ApiModule.java#L86) to check if its DEBUG build then set level as HEADERS else set level as NONE.

**Comment by adi23arora** [comment]
@csoni111 Yes, I'll add that condition.

**Comment by adi23arora** [comment]
@csoni111 Should I change the level of DEBUG one to BODY
