### ISSUE TITLE
app throws error while accessing shares of own server on android phone

### ISSUE THREAD

**Issue by mohitsvnit** [amahi/android#307]
When I access shares of "Welcome to amahi" server it works fine.
But when I access shares of my own server, It shows connection error.

**Comment by octacode** [comment]
Can you put the logs of the error here?

**Comment by mohitsvnit** [comment]
java.net.ProtocolException: Too many follow-up request: 21

**Comment by octacode** [comment]
Was not able to replicate the issue. Closing this for now

**Comment by mohitsvnit** [comment]
I can upload video of it if you like.

**Comment by csoni111** [comment]
@mohitsvnit you must be missing the installation of Amahi Anywhere app on your hda. Got to apps tab on hda dashboard and install `Amahi Anywhere` from the list to resolve this error.

**Comment by cpg** [comment]
We should handle this error better in the app, so as the user is not left confused.

While it may not be common that the AA server is not running, it can happen. The app should do the best of it, I think.

It should be easy to test by stopping the server for a bit and handle it with a nice, clear, message in the app.

**Comment by mohitsvnit** [comment]
@csoni111 My amahi server was running. But you are right I didn't installed any app in it yet.
@cpg Is there any way to check if `Amahi Anywhere app` is running or not?

**Comment by mohitsvnit** [comment]
@csoni111 You were right. It's an problem of not running `Amahi anywhere`.
Also I found out that in `ServerShareFragment` there is not action if  `serverClient` is not connected while getting shares. That is what happening if `Amahi anywhere app` is not running. So progress dialog keep rotating for infinite time. 
@cpg Should I add error msg in errorLinearLayout or show that in `SnackBar`?

**Comment by mohitsvnit** [comment]
`serverClient` was not connecting because `ServerRouteResponse` is failing. There is no action when that is happening.
I am thinking to add toast with message `Your Amahi server may not be running Amahi Anywhere. Please ensure the Amahi Anywhere app is installed and running.` when `ServerRouteResponse` is failed. 
@cpg @csoni111  what do you think?
