### ISSUE TITLE
Replace PNG files with vector ones

### ISSUE THREAD

**Issue by ArihantJain456** [amahi/android#314]
## Description

Currently, there are a lot of png files which contribute to increase in apk size. Replacing possible ones with xml files would be better approach towards saving space and backward compatibility.

### Would like to work on this issue?
Yes.

@csoni111, @cpg   please share your suggestions.

**Comment by cpg** [comment]
* how many is "a lot" of png files?
 * what is the difference between the apk size if you change TWO of them to what you propose?
 * why xml? what format? svg?

**Comment by ArihantJain456** [comment]
- For mobile, there are about 4-5 png images that can replaced easily through converters 
- For Android TV, there are more than 10, but converters may not be able to convert them properly.
- They may not decrease apk size much but they have the advantage of scaling.
- Android studio had good support for XML drawables(Vector Drawables).

**Comment by cpg** [comment]
Without doing the math, this does not seem like a big win. Especially since the video library is so large. I think we should postpone this. In the interest of cleaning the issues board, I will close this for now and we can reopen it later.

**Comment by cpg** [comment]
Without doing the math, this does not seem like a big win. Especially since the video library is so large. I think we should postpone this. In the interest of cleaning the issues board, I will close this for now and we can reopen it later. Thanks for the suggestion.
