### ISSUE TITLE
Force Close when clicked on 'Videos', 'Demo' or 'Introduction' in 'Shares' option

### ISSUE THREAD

**Issue by sanjitchak** [amahi/android#316]
This following line of code in **activity_server_files.xml** is causing the problem. It can't **inflate** this below fragment:

`<fragment
    android:id="@+id/castMiniController"
    class="com.google.android.gms.cast.framework.media.widget.MiniControllerFragment"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_alignParentBottom="true"
    android:visibility="gone"
    tools:layout="@layout/cast_mini_controller" />`
 
My phone info:-
Phone name - Mi 4a
Android OS: 6.0
Everything updated.

I tried using fragment manager to inflate it.
I tried changing 'class' to 'android:name'. 

**Proposed Changes :-**
We can implement the following to play video:- 
https://developer.android.com/reference/android/widget/VideoView.html
or
https://developer.android.com/reference/android/media/MediaPlayer.html

**Comment by csoni111** [comment]
Same as issue #297.
Add `chromecast.app.id` in your `api.properties` file. You can find the id in `api.properties.sample`.

**Comment by sanjitchak** [comment]
Thanks for the info! Fixed it!
