### ISSUE TITLE
Wrong Item Select Behavior in Navigation Drawer

### ISSUE THREAD

**Issue by ArihantJain456** [amahi/android#317]
## Description
Only one item should be highlighted at a time but it seems on selecting new item all previous item is highlighted too.

![bug](https://user-images.githubusercontent.com/23583851/37257897-3c118c4a-2595-11e8-910a-1538b80dce7e.jpg)

### It should work like this -
![should work](https://user-images.githubusercontent.com/23583851/37257898-3c3c42b4-2595-11e8-9bfa-853bc4eccd0c.jpg)

### Would you like to solve the issue?
Yes

@cpg, @octacode please share your views.

**Comment by sanjitchak** [comment]
In my case, the **Apps** comes for a brief moment and then disappears. 

How are you getting your own name **arihant** in the drawer? In my case, it's showing **Welcome to Amahi**, after signing in.

**Comment by ArihantJain456** [comment]
It's my amahi server.

**Comment by ArihantJain456** [comment]
@octacode give your reviews for the PR #318 .
