### ISSUE TITLE
Auto upload stuck disabled

### ISSUE THREAD

**Issue by cpg** [amahi/android#321]
I am not sure how I got into this situation in the app, but I tried enabling it, which worked, then I think I maybe had WiFi disabled and the app was having trouble accessing my server list. I had to close the app, the enabled WiFi and ran the app again.

Servers were there, browsed about and tested a bugfix. Went to Settings > AutoUpload and cannot enable it any more. Restarting the app does not not help, seems permanently stuck.

This means there is some state somewhere and it's not managed well!

**Comment by ArihantJain456** [comment]
Can I work on this issue? @cpg
