### ISSUE TITLE
Remove Chuck

### ISSUE THREAD

**Issue by cpg** [amahi/android#322]
We decided that Chuck is a little too intrusive and that the `logcat` is enough to debug.

This issue is to remove it from the stack.

**Comment by adi23arora** [comment]
Can I work on this?

**Comment by cpg** [comment]
There was a thought by @csoni111 that we should just comment it out so that it does not get compiled but add directions in the README for developers on how to add it/use it.

I'm fine either way.

**Comment by adi23arora** [comment]
Chuck not even displays the current requests and responses but also stores them in a DB so that these can be accessed later too. It can prove to be useful in some cases.

So, I guess I should just comment it out currently and add directions to re-enable it in Readme.
