### ISSUE TITLE
Add shuffle to player

### ISSUE THREAD

**Issue by cpg** [amahi/android#323]
A useful feature for the (already excellent) audio player would be to add random shuffle to play files in a given folder in random order over time.

This would allow users to have folders for specific music that they like (e.g. workout music) but not having it in the same order.

I am not sure what is the best UI. Maybe pressing long on the play button offers two options? 1) option `Play in Order` to play in the current sort order for the folder or 2) `Shuffle` to play in an order that is random forever (maybe 3) `Cancel`?)

**Comment by csoni111** [comment]
I think we should switch to [ExoPlayer](https://github.com/google/ExoPlayer) for playing music as per #165. It offers inbuilt support for playlist, shuffle, and many others.

**Comment by csoni111** [comment]
We can also add a feature to allow browsing the rest of the app while the music is playing. This can be made possible by building a mini controller of sort which can remain visible at the bottom of the screen as in Google Play Music app. This will be easier to build if we have ExoPlayer in effect.

**Comment by ArihantJain456** [comment]
ExoPlayer is good for videos too, so by adding ExoPlayer we may not need videolan lib.

**Comment by sanjitchak** [comment]
Is anyone working on adding exoplayer?
