### ISSUE TITLE
Java8 features

### ISSUE THREAD

**Issue by ArihantJain456** [amahi/android#326]
## Description
We should make use of new Android Studio supported Java8 features like lambda Expressions.
for example:
`button.setOnClickListener((View view) -> 
// do something`

They are easier to use and also helpful in writing cleaner code.

**Comment by cpg** [comment]
Can you guys make an assessment of how large of a transition task this is?

It's probably a nice-to-have, though not a high priority if it's a complex task.

**Comment by ArihantJain456** [comment]
This includes:
1. Changing all listeners. (Easy)
2. Understanding code properly for applying [Method References](https://docs.oracle.com/javase/tutorial/java/javaOO/methodreferences.html). (May take 2-3 hrs)
3. Finding methods wherever [lambda expressions](https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html) can be applied. (may take 2 -3 hrs )
4. Testing all features of app (may take 1 hr).

**Comment by ArihantJain456** [comment]
@octacode what do you say ? should I implement this?

**Comment by adi23arora** [comment]
I think this would be a great transition. But after that, we need to have strict contributing guidelines to follow this style throughout the project to maintain uniformity.

**Comment by ArihantJain456** [comment]
This new style will make the code more simple and cleaner and using this java8 is not too difficult. In all projects, uniformity in code is necessary for easier understanding of code. In Amahi too, coders have followed some uniform pattern and we all are following it. @adi23arora

**Comment by ArihantJain456** [comment]
@octacode current compileSDKVersion is 25, can I update it to 26 to use some of its features?
