### ISSUE TITLE
app crashes when any of the options among "Demo","Share" or "Introduction" selected.

### ISSUE THREAD

**Issue by advir29** [amahi/android#337]
app crashes when any of the options among "Demo","Share" or "Introduction" selected from shares option from drawer under welcome to amahi selection.

**Comment by adi23arora** [comment]
@advir29 You should be careful while sharing logs. Refrain from sharing complete logs because it may expose the API endpoints and can also leak some other sensitive info like your username and password in the requests, as you can see in this case. 
So, remove this log file ASAP.

**Comment by ArihantJain456** [comment]
@advir29 It seems you haven't put chromecast app id in api.properties  from [here](https://github.com/amahi/android/blob/beta/api.properties.sample)

**Comment by csoni111** [comment]
@advir29 Check issue #316

**Comment by advir29** [comment]
Thanks @ArihantJain456  for advice regarding log file attachment
