### ISSUE TITLE
To create an QR code based guest login system to HDA with viewing rights for a specified time limit.

### ISSUE THREAD

**Issue by advir29** [amahi/android#340]
We can provide an option for admin to generate a QR code and let any of its guests login to his HDA from their Android or iOS device just by scanning it in his amahi app. The admin can specify a time limit for newly added guest or else a default value say "3 hrs" are allocated to new guest user. 
The guest could view the shared which are configured to be "available to guest" beforehand; like "movies" or "songs".

**Comment by advir29** [comment]
Can I work on implementing this?

**Comment by octacode** [comment]
This involves a lot of back-end code and newer APIs not only this there will some security issues with this one. We need to plan this properly before. 

Also with this approach If I want to provide access to a device which I don't have physical access to then what?

Will reopen this one later. :)
