### ISSUE TITLE
Files & folders highlighted on click

### ISSUE THREAD

**Issue by adi23arora** [amahi/android#341]
### Current Scenario:
In the `ServerFilesFragment`, files and folders are highlighted on click and it remains in the activated state even on resume. (As shown below)

![issue-highlight1](https://user-images.githubusercontent.com/17095968/37739660-dfc82acc-2d80-11e8-849a-4b51f6ff44e0.png)

This might confuse the users with the items being checked on a long press for the Action Menu. (As shown below)

![actual-highlight1](https://user-images.githubusercontent.com/17095968/37739659-df55453e-2d80-11e8-9edb-177f0b77b122.png)

This might lead to a bad user experience.

### Suggested Changes:
Disabling item check on click and using only Ripple effect to highlight clicks.

**Comment by ArihantJain456** [comment]
If we replace listview with recyclerview then the problem is automatically solved as done in #325.

**Comment by adi23arora** [comment]
@ArihantJain456 I have re-tested this after PR #325 was merged. I was still able to replicate this issue.

![issue-highlight2](https://user-images.githubusercontent.com/17095968/37804921-e11502e2-2e5c-11e8-9c17-b5d8e242a672.png)

 This problem can't be solved automatically just by replacing ListView with RecyclerView. Although it seemed to be, as the folders are refreshed every time on resume.

I will send a PR with fix soon.

**Comment by cpg** [comment]
I don't think this works at the moment (perhaps after the merges we did a few minutes ago).

Could you review?

**Comment by adi23arora** [comment]
I re-tested with the current beta branch and issue still persists.

Steps to reproduce:
1. Click on any file. (File opens/plays)
2. Return back to the folder, file is still highlighted.

Issue: File should not be highlighted or activated in the first place.
