### ISSUE TITLE
No dividers between RecyclerView list items

### ISSUE THREAD

**Issue by adi23arora** [amahi/android#347]
In some of the recent commits from #325, ListView in `ServerFilesFragment` was changed to RecyclerView. But the dividers which were present by default in ListView are missing in RecyclerView.

![no-divider](https://user-images.githubusercontent.com/17095968/37806548-a42d1c7a-2e66-11e8-8c5a-6592b228a140.png)

These dividers are often used to separate different list items and specify the boundaries of each list item layout which is clickable. This holds good for a positive user experience.

**Comment by octacode** [comment]
```
DividerItemDecoration dividerItemDecoration = new DividerItemDecoration(recyclerView.getContext(), layoutManager.getOrientation());
recyclerView.addItemDecoration(dividerItemDecoration);
```

This might be able to do the task
