### ISSUE TITLE
Wrong modification time

### ISSUE THREAD

**Issue by ArihantJain456** [amahi/android#351]
## Description
<img src="https://user-images.githubusercontent.com/23583851/37829231-4a011770-2ec4-11e8-878f-923d65b3031e.jpg" width="200px"> 
you can see  that the first photo's modificaton time is 24th march.
But in India, it is 23rd March.

**Comment by mohitsvnit** [comment]
Maybe it's not considering local time zone.

**Comment by ArihantJain456** [comment]
Maybe just because of Wrong Server time. Closing it.
