### ISSUE TITLE
No direct Download option

### ISSUE THREAD

**Issue by ArihantJain456** [amahi/android#355]
## Description
For videos, audios, and images there is no direct option for downloading.
If a user wants to download a file then only way around is to click on share option.

### Solution 
 Download option can be added to the action bar along with other options.

**Comment by ArihantJain456** [comment]
We can save downloaded files in external storage in Public files so even after uninstalling the app, they will be there to be used by other apps.

**Comment by cpg** [comment]
Well, we can. I was asking more along the lines of "what is typically done in Android for something like this? .. is there a file system view to the user?"

In this case, are users aware of a "public" area commonly in Android?

**Comment by ArihantJain456** [comment]
In most Android apps, like in Google drive and one Drive, the downloaded file gets saved in the Download folder. In some apps, the file gets saved in a folder according to its type: music file in the music folder, picture in the pictures folder. I was thinking of saving the file in the download folder.

**Comment by cpg** [comment]
How about we get going on the feature, assuming the destination is the download folder, and later change the location according of the advice from @octacode, @megabitdragon and any others that are regular users?

**Comment by sanjitchak** [comment]
I think we may later change the destination to 'Amahi' folder, with separate folders for separate file types (images , videos, documents, etc).

'Whatsapp' store all our downloaded media in its own folder name.  
![screenshot_2018-05-03-11-40-10-607_com estrongs android pop](https://user-images.githubusercontent.com/20724062/39561956-9b45cf1e-4ec6-11e8-974a-01fadfbd9d23.png)

**Comment by cpg** [comment]
I just had this idea: what if the folders in the file system where these files are stored (even if we did not download anything) were to be browsable as _a share_?

So, basically we could play the files again with the app itself! Or share them, etc.

We could make up a "virtual share" called `Android Phone Storage` or something like that, and we'd see it all the time after the first time a file has been downloaded? (or even before, we always present that virtual share, if it's simpler)

**Comment by megabitdragon** [comment]
We can do something like netflix where we have a download option for audio/video files and have a "share" like @cpg suggested. On top of that we can make something more transparent to the user. For example we could only show files that have been downloaded in their original share. A real life example will be: I need to get on plane and I download some songs for the takeoff. Once I switch to airplane mode, the app should work the same way but only files that are on device should be available. The difference is that they will not be in a special share but in the original share.

**Comment by ArihantJain456** [comment]
@megabitdragon idea looks good. 
With the idea of @cpg of making a toggle instead of a button for download makes it more precise.
So there will be a separate share as @cpg suggested say `Offline Data`, and on opening the app when the internet connection isn't available, the user will only see the `Offline Data` share containing original share with downloaded files.

**Comment by ArihantJain456** [comment]
<img src="https://user-images.githubusercontent.com/23583851/39615190-80279380-4f92-11e8-9254-2e35ae154ab9.jpg" width="30%">

In youtube app,
<img src="https://user-images.githubusercontent.com/23583851/39615191-8053de36-4f92-11e8-9a15-bce9a1fa9cce.jpg" width="30%">
This seems good to me. We can shift all the options of the action bar in the dialog.

**Comment by ArihantJain456** [comment]
- There will be a `more option` <img src="https://user-images.githubusercontent.com/23583851/39620478-f702aa06-4fa8-11e8-8343-3ab81a788925.png" width="15"> for each item in the list as shown 
<img src="https://user-images.githubusercontent.com/23583851/39619953-2e214f08-4fa7-11e8-9cbc-68329c5a0b5f.png" width="30%">

- On Clicking <img src="https://user-images.githubusercontent.com/23583851/39620478-f702aa06-4fa8-11e8-8343-3ab81a788925.png" width="15">, it will display the list of options that can be applied to the file, like delete, `download`, share.<img src="https://user-images.githubusercontent.com/23583851/39620027-68e21262-4fa7-11e8-949a-ffedf76d194c.png" width="30%">
- Download will start on clicking download. A snackbar or a dialog will appear after the completion of download process indicating successful download.
- If the file is already downloaded and <img src="https://user-images.githubusercontent.com/23583851/39620478-f702aa06-4fa8-11e8-8343-3ab81a788925.png" width="15"> is clicked, then it will show the `Delete from downloads` option instead of `Download` option.
- As @cpg suggested, there will a separate `My Downloads` share showing all the downloaded/downloading files with their current state. Each file will have the option to play, delete,share.

**Comment by cpg** [comment]
Got it. Thanks for expanding the details. So let's split this into several (maybe two, maybe three?) steps and focus one at a time.

**Comment by ArihantJain456** [comment]
This can be broken down into these steps:
1. adding option dialog and option button<img src="https://user-images.githubusercontent.com/23583851/39620478-f702aa06-4fa8-11e8-8343-3ab81a788925.png" width="15"> and also adding the download option and download completion snackbar.
2. Implementing a DB for storing list of downloaded files. This will be used to check whether a file is already downloaded, updated or downloading. So according to its state options will change. 
3. Adding `My Downloads` share. This will display list of all downloaded files with options to play, share and delete from local storage.

**Comment by megabitdragon** [comment]
That's a good point @csoni111. I wonder if there is any way to prevent that. Also, what if someone removes the file from the HDA, what are we going to do? Delete the file from local storage? Restore it? Ask?

**Comment by octacode** [comment]
For this what Google drive does is that it keeps the downloaded file in the local storage even if the file is deleted from the cloud storage.

**Comment by cpg** [comment]
Good points. Lots of cases. In my view, we have to define:

* a precise set of valid states (icons reflect the state to the user)
* allowable transitions (what the user is allowed to do)

This is akin to a cache coherency protocol - defining how things can diverge and how to manage the evolution of those states.

**Comment by ArihantJain456** [comment]
Valid states can be:
- Not Downloaded
- Downloading
- Downloaded
- Changed from the HDA (an update option can be provided in place of download option)
- Changed from the local storage (an option to upload the file can be shown)
- Downloaded but deleted from the local storage (For this, simply deleting the entry from the local database and changing state to Not Downloaded looks fine)
- Downloaded but deleted from  HDA (For this, the file should be available in the `My Downloads` share only)



There are two ways proposed for the issue.
1. mentioned by @cpg: [here]( https://github.com/amahi/android/issues/355#issuecomment-386465338)
- this includes showing different icons according to different downloading states.
2. mentioned [here](https://github.com/amahi/android/issues/355#issuecomment-386546162)
- this includes showing a dialog box for different options available to the user for the selected item.

I think, its necessary to decide one among the two ways before discussing any further.

**Comment by cpg** [comment]
I think your suggestion, option 2, is a good idea and more extensible.

As for the states, would you consider trying to formally draw a state machine with valid transitions within states? It may be a little bit of work up front, but I think it will help in the long term.

Would be great if we can make it editable to we evolve, for example using dot. Below is a start to that (assuming a file called `download-states.dot). Get a PNG file with `dot -o downloaded.png -Tpng download-states.dot`

```dot
digraph download_states {
        rankdir=LR;
        size="8,5"
        node [shape = doublecircle]; online;
        node [shape = circle];
        online -> downloading [ label = "get it" ];
        downloading -> online [ label = "dl failed" ];
        downloading -> downloaded [ label = "dl completed" ];
        downloaded -> remote_updated [ label = "hda updated" ];
        downloaded -> local_vanished [ label = "local removed" ];
        downloaded -> remote_deleted [ label = "remote removed" ];
}
```

**Comment by cpg** [comment]
Latest state diagram for discussion
![download_states_diagram](https://user-images.githubusercontent.com/9907/39790612-ed8a109a-52eb-11e8-9d21-a37174caead0.png)
