### ISSUE TITLE
App crash when I tried to open offline file after fresh installation

### ISSUE THREAD

**Issue by codedentwickler** [amahi/android#375]
I set up and ran the current beta branch on my Android device, app crash when I tried to open offline files when I just installed it. Maybe because I have not downloaded any file for offline yet. 

How to reproduce
- Uninstall Amahi android
- Do a fresh reinstallation from the beta branch
- Try to open offline files on reinstallation

It seems to happen repeatedly

**Comment by ArihantJain456** [comment]
same as #297

**Comment by codedentwickler** [comment]
resolved in #297
