### ISSUE TITLE
Offline folder is not accessible in offline mode

### ISSUE THREAD

**Issue by codedentwickler** [amahi/android#377]
When the app is launched with no internet connectivity or in airplane mode, the offline folder is not accessible, only an error message "Connection Error" shown in the Navigation Drawer. This defeats the purpose of making the files available offline in the first instance.

We can replace this error message with a text indicator maybe `Currently Offline` and show the offline folder in the Navigation Drawer.

**Comment by ArihantJain456** [comment]
We can solve it this way:
1. If no server is selected, this means the user is opening the app for the first time. If there is no internet connection, we can show the same network error.
2. If a server is selected before. We can show the selected server and offline files option, and a text saying offline.

**Comment by njnaman** [comment]
if this issue is open can i work in this?

**Comment by chirag-jn** [comment]
This issue doesn't exist anymore.
