### ISSUE TITLE
Fixing app flow after clicking signout button in settings page

### ISSUE THREAD

**Issue by sukhbir-singh** [amahi/android#38]
After clicking on sign out button in settings page, app gets redirected to login page. But then if user presses back button it reopens main activity, whereas as per expected behavior after login page appearance. Back button should close the app.

**Comment by sukhbir-singh** [comment]
Refer PR#39

**Comment by pranavgupta1234** [comment]
@sukhbir-singh  I think we can clear the activity stack and open login page after that.For that we can set flags on intent like i.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK) before starting the activity

**Comment by sukhbir-singh** [comment]
Yes I have done the exactly same thing in pull request #39
