### ISSUE TITLE
Logo Proposal for Project Enhancement

### ISSUE THREAD

**Issue by debpedrano** [amahi/android#392]
Good day PO,

This repo is getting bigger and I am offering you logo design for the repo, everything is for free. I just want to contribute and gain more knowledge about graphics.

Is there any chance I can open up this issue and have your permission to create a logo?

**Comment by octacode** [comment]
@cpg it won't do us any harm to have a fancy logo for our repo. Your views please

**Comment by debpedrano** [comment]
I'll create a simple but attractive logo for you

**Comment by cpg** [comment]
We will need to know what are the conditions/license of use. We get it that you are doing it to promote and/or enhance your skills, however, we need to know the details. Thanks!

**Comment by debpedrano** [comment]
Any license is good and you don't need to pay me. All you need to do is to give me the details/information or your perspective design.

**Comment by cpg** [comment]
What do you need from us?

We have have always wanted a "flat" version of [our logo](https://www.amahi.org/press-kit). We had some prototypes of it, but never really deployed.

**Comment by debpedrano** [comment]
the project already had a beautiful logo, and I think that's the best one. Thanks!
