### ISSUE TITLE
(Building Error)Android Gradle plugin supports only Crashlytics Gradle plugin version 1.25.4 and higher.

### ISSUE THREAD

**Issue by iamrmrishan** [amahi/android#394]
I got an issue when building, I got this error 
> TheAndroid Gradle plugin supports only Crashlytics Gradle plugin version 1.25.4 and higher. Project 'android' is using version 1.22.1

and I changed the build.gradle file    `classpath 'io.fabric.tools:gradle:1.22.1'` to `classpath 'io.fabric.tools:gradle:1.25.4'.` and the app was built with no error.

should I create a pull request?

**Comment by cpg** [comment]
> should I create a pull request?

Yes please, that is the way to contribute. Thank you.

**Comment by iamrmrishan** [comment]
okay

**Comment by ArihantJain456** [comment]
@iamrmrishan 
You must have updated the grading plugin version, otherwise, you will not get this problem.

**Comment by cpg** [comment]
Looks like potential user error.
