### ISSUE TITLE
Place `google()` repository as the first priority repository

### ISSUE THREAD

**Issue by RajaVamsi11** [amahi/android#397]
In build. gradle file jcenter() repository have first priority than google() repository. My idea is to Place `google()` repository as the first priority repository to avoid such errors like 
                **Failed to resolve: multidex-instrumentation**
  Here is link to check to solve this error [https://stackoverflow.com/questions/45608362/android-studio-3-0-beta-1-failed-to-resolve-com-android-supportmultidex1-0-2](here)

**Comment by RajaVamsi11** [comment]
@ArihantJain456 Here jcenter() is at first priority. We have to change this also.

**Comment by ArihantJain456** [comment]
@RajaVamsi11  ok, go ahead.
