### ISSUE TITLE
Translations for the app in Hindi and Malayalam

### ISSUE THREAD

**Issue by gopikaharikumar** [amahi/android#400]
**Summary**

This application does not have translations for Hindi and Malayalam

**Steps to reproduce the issue**

1. Go to settings of your phone
1. Change the language to Hindi or Malayalam

**Observed Behaviour**

The language does not change to Hindi or Malayalam.

**Expected Behaviour**

The language should change to Hindi or Malayalam.

**Phone and Android version**

Vivo V11 
Android 8.1.0
Funtouch OS 4.5

**Comment by gopikaharikumar** [comment]
May I please work on this issue?

**Comment by octacode** [comment]
I was able to review the Hindi strings :+1:
