### ISSUE TITLE
Missing Issue Template  

### ISSUE THREAD

**Issue by gopikaharikumar** [amahi/android#401]
This repository is missing an issue template. Issue template allows the contributor to express their  issues in a much better way.

**Comment by gopikaharikumar** [comment]
May I work on this issue?

**Comment by RajaVamsi11** [comment]
@gopikaharikumar It has been four days. I don't think adding issue template will take that long.
@cpg Can I work on this issue if it is not a problem to @gopikaharikumar

**Comment by RajaVamsi11** [comment]
@gopikaharikumar You can close this issue as @cpg added templates of both issues and pull requests.
