### ISSUE TITLE
It should Show an empty view when there's nothing to show on the Home Page

### ISSUE THREAD

**Issue by iadeelzafar** [amahi/android#411]
I made an account on Amahi's website and then when I logged in using the mobile app it shows nothing when there are no HDA files on the Home Page. 

<img src = "https://user-images.githubusercontent.com/36811908/52166320-8a5ef000-272d-11e9-817e-6fd63ca7b09c.jpg" height="550" width="329">

It will be much better if it shows an empty view. An empty view to mention something like "You haven't added any HDA file yet"
For example:
This is just an example. I'll make a decent one.

<img src="https://user-images.githubusercontent.com/36811908/52124584-7a6edf80-264b-11e9-816b-30aa4e5de1f5.png" height="550" width="329" >

**I'd love to work on this. Just let me know if I can start working on this.**

**Comment by iadeelzafar** [comment]
I'd love to work on this. Just let me know if I can start working on this.

**Comment by Sreyas-108** [comment]
Its been more than 24 days since this issue has been raised. Can I work on this issue as my first contribution?

**Comment by Sreyas-108** [comment]
Its been more than 24 days since this issue has been raised. Can I work on this issue as my first contribution? @cpg

**Comment by cpg** [comment]
@iadeelzafar for something relatively simple like this there is no need to ask for permission and just wait. Best is to do it and submit a PR for review/merging. We were busy.

@Sreyas-108 ... in deference to @iadeelzafar, we should let him have a chance to work on it if he is still interested. If he does not reply in a few hours/days, we can go ahead.

**Comment by iadeelzafar** [comment]
@Sreyas-108 Go ahead. Good Luck!

**Comment by chirag-jn** [comment]
In accordance with #449, we are now showing shares on the home page. So we don't have to show an empty state screen anymore.

**Comment by cpg** [comment]
We don't need this any more because we show shares.
