### ISSUE TITLE
Issues with HomeUp button

### ISSUE THREAD

**Issue by octacode** [amahi/android#42]
When inside a directory Home up button directly takes the user to the list of shares instead of taking it in the upper folder.
For Example :- if we are in Demo/music and if home Up is pressed. We'll be redirected to the Shares fragment instead of Demo.
I am sending a PR for this.
Thanks

**Comment by cpg** [comment]
I remember there was some discussion about this when we created the app and I think it was determined that navigation back was to be done with the proper "back" button, and the home button was to be to take the user to the top level of the app navigation.

I would like to seek the advice of people with expertise of what matters with the latest best practices on this. @megabitdragon may have a good opinion.

**Comment by adithya321** [comment]
We can have a Home icon to take the user to the top level like [Amaze File Manager](https://play.google.com/store/apps/details?id=com.amaze.filemanager).

<img width="515" alt="amaze" src="https://cloud.githubusercontent.com/assets/3854934/24161480/87809ea0-0e8a-11e7-8cfb-38a54edba0f8.png">

**Comment by octacode** [comment]
@cpg you views on this??

**Comment by cpg** [comment]
Based on [the guidelines](https://material.io/guidelines/patterns/navigation.html#navigation-usage), it seems like

- the up button (at the top, inside the app header), should be hierarchical. In other words, take the user one level "up" in the hierarchy within the app. We are not doing this at the moment.
- the back button (at the bottom, possibly a hardware button) should be chronological. I have heard this is kept automatically. I am not sure if we do anything in the app about this. We probably should *not* if it's kept automatically?

Note: there is the subtle question about the meaning of "screen" in the guidelines. When the user is navigating in our app -- is she presented with a new "screen" when they enter a share and a folder or more inside a share and a folder? Or is she in the same "screen" with different content?

My feeling is that each share and folder should be considered a "screen" for our purposes.

What does #43 do in this respect, and does it match the guidelines and our interpretation of them in my comments above?

**Comment by octacode** [comment]
When the user navigates from Share to a folder that's when a new screen is presented. However, When the user navigates from folder to another folder(nested) then the screen remains same but the content is updated.
I too feel we should consider each folder and share as a new screen.
If we consider each folder and share as a new screen then #43 matches the guidelines.

**Comment by cpg** [comment]
I see the back button does not seem to be chronological at the moment.

Does the app control it?

If so, can we just not do anything and get it working chronologically as it's meant to be?

**Comment by octacode** [comment]
No. It's controlled by android by default. However.... We can control it by overriding the OnBackPressed() method in the Activities. Can you please explain where the Back button violates the chronological order?
