### ISSUE TITLE
Stuck on Intro activity in Android TV

### ISSUE THREAD

**Issue by chirag-jn** [amahi/android#422]
**Describe the issue**
When I tried running the app in Android TV via emulator, I was not able to go past the intro activity on clicking Get Started.

**To Reproduce or Feature details**
1. Run the app on an Android TV / Android TV Emulator
2. Continue with the intro activity.
3. Click on Get Started and you will return to the same intro activity.

**Expected behavior**
It should load the login screen after completing the intro activity.

**Screenshots**
![amahi-tv](https://user-images.githubusercontent.com/31701616/53592132-a08c8e80-3bbb-11e9-8827-48dcfb24df20.gif)
The quality was quite reduced in the gif though.

**Smartphone (please complete as much of the following information as possible):**
 - Device: Android TV (720p) API 26 (Emulator)
 - Android 8.0

**Comment by octacode** [comment]
@chirag-jn, Please go ahead and fix this issue.

**Comment by chirag-jn** [comment]
Sure @octacode. Trying to solve this issue right now.

**Comment by adi23arora** [comment]
Can I work on this? it's open for a while now.
