### ISSUE TITLE
blank screen when back button presses on navigation activity

### ISSUE THREAD

**Issue by zedlabs** [amahi/android#423]
when back button is pressed twice (1st to remove nav. drawer,2nd to exit app) after running the app from android studio, a blank screen appears.It only appears if the app is launched from android studio

1. Run the app from android studio,select device
2. on the default activity(navigation activity) press back twice

**Expected behavior**
App should close

![ggu](https://user-images.githubusercontent.com/32540498/53637216-982e6500-3c48-11e9-8ff3-d15338776be5.gif)

 - Xiaomi mi A2
 - OS: Pie

**Comment by cpg** [comment]
I vaguely recall that the part about the app not exiting [was on purpose](https://github.com/amahi/android/issues/249) because it was too easy to exit and other apps would not exit so easily.

Do you think things have changed since then and we should exit?

**Comment by zedlabs** [comment]
in the android UI guidelines it specifies that if any data(form,login info etc.) is not lost, then back button should exit the app otherwise if some data is present common practice is to display a toast message with "press back again to exit" to confirm from the user

**Comment by octacode** [comment]
I remember discussing this "Press back again to exit" toast message for exiting the app before. We decided not to go with it back then. 

Also, I too think that pressing back button should close the app when the navigation drawer is being displayed since, our home screen is empty. 

Or, we can show the list of shares on the home screen when the app is launched then we don't have to change anything or add a toast message, the way Gmail app does it

**Comment by stupidly-logical** [comment]
@octacode I second you suggestion to show the list of share on the home screen as it is blank as of now. Would like to work on it if it is okay. @cpg

**Comment by cpg** [comment]
@stupidly-logical Let's give the option to work on a fix to this first to @zedlabs. He was the one suggesting the issue, etc.

As to what needs to be done, I think we should do what most apps do and if they do what the guidelines suggest, all the better.

**Comment by stupidly-logical** [comment]
Cool. :peace_symbol:

**Comment by zedlabs** [comment]
I would suggest creating  a new home activity as default which includes lists from shares and recent files, this is a common way with many recent apps.

**Comment by shivammaindola** [comment]
@zedlabs Are you working on this issue?

**Comment by zedlabs** [comment]
@shivammaindola you can work on it if you want

**Comment by shivammaindola** [comment]
@zedlabs  Ok Thanks.

**Comment by nileshteji** [comment]
When can use a ALert Dialog if this is caused due to closing of the application
