### ISSUE TITLE
Implementing Animation in RecyclerView

### ISSUE THREAD

**Issue by shivammaindola** [amahi/android#428]
![video2gif_20190306_181602](https://user-images.githubusercontent.com/39567362/53882656-f38f9700-403c-11e9-9c99-773bd4d4974e.gif)

@cpg @octacode Can I add animation in above list while scrolling? I think, it will look preety cool.

**Comment by cpg** [comment]
Please go ahead. There is really no need to ask for permission, especially for smaller things (which I believe this may be).
