### ISSUE TITLE
Error coming while scrolling Recent files 

### ISSUE THREAD

**Issue by shivammaindola** [amahi/android#431]
_**Summary**_
I opened more than 20 files(including music, photos, videos, etc), clicked on Recent files and scrolled down. Suddenly App crashed and went back to the home screen.
Below is the gif of error.

![video2gif_20190307_184949](https://user-images.githubusercontent.com/39567362/54067235-c2dd7680-4263-11e9-9fa8-751eab76e2c8.gif)

**Device and android version**
Device: Redmi 6 pro
Android version: 8.1.0

**Comment by stupidly-logical** [comment]
I've investigated this issue a bit and so far I didn't get any relation between the crash and the scrolling or number of recent files. However a particular file is making it crash.

**Comment by stupidly-logical** [comment]
It was due to getLastPathSegment() behaviour. Details: #433

**Comment by shivammaindola** [comment]
Nice, it solved.
