### ISSUE TITLE
Add an option to ask for password or pattern everytime application start

### ISSUE THREAD

**Issue by shivammaindola** [amahi/android#453]
To make our application more secure, we can add the privacy feature in settings where a user can set his own password or a pattern to unlock the app during startup. User can disable or enable this feature from the settings at any time.

It will look like this.

![lock](https://user-images.githubusercontent.com/39567362/54842316-a4fa2200-4cf7-11e9-8f85-4c45d27279a7.gif)

**Comment by shivammaindola** [comment]
@cpg @octacode @csoni111 can I start working on this?

**Comment by shivammaindola** [comment]
@codedentwickler any thought?

**Comment by chirag-jn** [comment]
@shivammaindola are you working on this? 
@cpg in my opinion, having a security feature is a nice add-on if the user wants it as it will give one layer of protection while someone tries to access the files stored on the server.

**Comment by shivammaindola** [comment]
@chirag-jn  Yes, I'm trying to implement a fingerprint authentication security feature, will send a PR soon.

**Comment by cpg** [comment]
Not too practical
