### ISSUE TITLE
Audio controller fragment is displaying for a fraction of seconds

### ISSUE THREAD

**Issue by shivammaindola** [amahi/android#456]
ServerFilesActivity is showing an audio controller fragment at the bottom of the screen for a fraction of second.

**Expected behavior-** When no song is playing, it should not show the audio controller fragment at the bottom of the screen. 

This gif is playing at 0.5x to show the actual error.

**Gif of the error-**
![video2gif_20190327_232900](https://user-images.githubusercontent.com/39567362/55100852-da808000-50e8-11e9-9ae1-7fae8a9b3b94.gif)

**Comment by adi23arora** [comment]
@shivammaindola I also encountered the same issue, it shows that audio controller on start of every fragment. It has a bigger consequence, if you are playing any music in background, it abruptly stops that on the start of every fragment .
Are you working on fixing this?

**Comment by shivammaindola** [comment]
Yes, @adi23arora I'm trying.
