### ISSUE TITLE
Incorrect placement of icon

### ISSUE THREAD

**Issue by chirag-jn** [amahi/android#461]
**Describe the issue**
The cross icon which appears while searching for a file in the files navigator doesn't appear to be correct in the landscape mode. 

**To Reproduce or Feature details**
Steps to reproduce the behaviour:
1. Go to Shares 
2. Rotate device to landscape mode.
3. Click on the search icon.
4. See the placement of cross icon.

**Expected behavior**
The cross icon should appear close to the sort icon as it is in the portrait mode.

**Screenshots**
![landscape](https://user-images.githubusercontent.com/31701616/55813873-2977dd80-5b0b-11e9-858c-2d5c69d7382f.jpg)
![portrait](https://user-images.githubusercontent.com/31701616/55813882-2bda3780-5b0b-11e9-9bc6-e5d8c17c6668.jpg)

**Smartphone (please complete as much of the following information as possible):**
 - Device: Vivo 1817
 - OS: Android Oreo 8.1

**Comment by balaji-ramavathu** [comment]
can I fix this?

**Comment by chirag-jn** [comment]
@balaji-ramavathu 
I have started working on this.

**Comment by balaji-ramavathu** [comment]
okay

**Comment by shivammaindola** [comment]
@chirag-jn are you working on this?

**Comment by ankushmundhra** [comment]
@chirag-jn can i work on this issue?
