### ISSUE TITLE
Query in the Search bar is not preserved on screen rotation

### ISSUE THREAD

**Issue by balaji-ramavathu** [amahi/android#462]
**Describe the issue**
In ServerFilesActivity, on screen rotation to landscape or from landscape to portrait mode, the activity is recreated, hence any query in the search bar gets lost.

**To Reproduce or Feature details**
1. enter any search query
2. Rotate to landscape

**Expected behavior**
Search query should not be lost.

**Screenshots**
![orientation-gone](https://user-images.githubusercontent.com/26673203/55829541-820ba280-5b2c-11e9-9fad-a89d0b68e2dc.gif)

I am going to fix this issue.

**Comment by vibhusharma101** [comment]
can I work on this issue @cpg
