### ISSUE TITLE
After selecting the server from the drawer, servers list is not closed

### ISSUE THREAD

**Issue by balaji-ramavathu** [amahi/android#464]
**Describe the issue**
After selecting the server from the server list in the navigation drawer, server list is still displayed instead of navigation items.

**To Reproduce or Feature details**
1. Select any server from the servers list.
2. open the drawer again
3. servers list is still displayed

**Expected behavior**
Servers list should be closed and the navigation items (Shares, Apps, etc.) should be displayed.

**Screenshots**
![server-list](https://user-images.githubusercontent.com/26673203/55864241-bc5f5900-5b99-11e9-8de5-6a992652c620.gif)

**Comment by chirag-jn** [comment]
What if we want to change the server after selecting one?

**Comment by balaji-ramavathu** [comment]
You can click on the server name again to select. Generally users don't shift from one server to other so quickly to make the list open for them. Instead, we need to show the shares, apps and other items so that user can access them quickly. You can see this practice in Google play store navigation drawer also. There, if you have two or more accounts and select one of them, the accounts list gets closed and navigation items will be shown.
