### ISSUE TITLE
Vim api.property settings

### ISSUE THREAD

**Issue by DoMINAToR98** [amahi/android#49]
url.amahi = URL
url.proxy = URL
client.id = ID
client.secret = SECRET
what is the value for URL SECRET and ID
I'm facing issues in Retrofit

**Comment by octacode** [comment]
@DoMINAToR98 I have mailed you the API keys .. 
P.S don't post these API keys on public groups. Cheers

**Comment by pranavgupta1234** [comment]
@octacode can you please mail these to me too ?

**Comment by DoMINAToR98** [comment]
thanks @octacode
