### ISSUE TITLE
Use of thumbnails instead of full image in files list/grid view

### ISSUE THREAD

**Issue by csoni111** [amahi/android#490]
Our backend server now supports generating 100 x 100 px (approx) thumbnails for all image files. We can use those thumbnails instead of the loading the full image in the list/grid view showing all files in a directory.
Docs for this are available [here](https://github.com/amahi/amahi-anywhere-specs#reading-files) under cache element. More on this is present [here](https://github.com/amahi/amahi-anywhere-specs#getting-thumbnails).

We can also use these thumbnails to show a blurred preview of the image while loading the original image in background in full screen. This can be done by showing a blurred and scaled version of the thumbnail in place of the original image when the image viewer is opened and as soon as the original image is loaded, replace the thumbnail with the original image.

**Comment by amitYadavDev** [comment]
can i work on this issue? @csoni111

**Comment by csoni111** [comment]
@amit6663  I guess its already done in this [pr](https://github.com/amahi/android/pull/495).

**Comment by cpg** [comment]
Merged already, thanks!
