### ISSUE TITLE
Showing connection error instead of wrong credentials on sign in page.

### ISSUE THREAD

**Issue by mr-volatile** [amahi/android#496]
![Screenshot_20190910-002617](https://user-images.githubusercontent.com/26926669/64558714-29059c00-d362-11e9-802b-d4b7ed30b262.png)

**Comment by mr-volatile** [comment]
And provide correct login credentials.

**Comment by mr-volatile** [comment]
Why there is no Signup/Register option??

**Comment by cpg** [comment]
Good point -- it should be pointed out in the app that the Amahi app needs a home server to be used. We put that in the description (IIRC; well, also in iOS, since I remember putting it), but it probably would be better in the app.

Also, the error should be corrected.

**Comment by vaandhare** [comment]
Thank you @cpg.
Can you please provide me correct credentials to access the app?

**Comment by cpg** [comment]
This is not the place to request them. Follow the details in the README please

**Comment by mr-volatile** [comment]
Hello @cpg 
This was my first PR, please can you merge this PR?

**Comment by balaji-ramavathu** [comment]
Hey @vaandhare you need to set API properties before building the app. You need to follow steps in README to do that. Seems like you haven't done that. This is the reason you are getting inappropriate error message. 

The app contacts with API via the internet to check the credentials. So it first checks if there is internet connection and only if the connection is available, it checks if the credentials are correct or not. For that, API properties need to be set.

**Comment by shrootis** [comment]
Same problem is with me..though net is on there is connection problem...So I am mailing to support team for url and details..

**Comment by shrootis** [comment]
This is something to keep private and you obtain it by sending a message to support at Amahi dot org.
I mailed but didnt get reply....is it support@amahi.org only na

**Comment by somenath1435** [comment]
@octacode @cpg @shrootis @balaji-ramavathu How to get secret key? Please elaborate

**Comment by spielers** [comment]
@somenath1435 message to support@amahi.org about credentials 
they will give 
url.amahi = URL
url.proxy = URL
client.id = ID
client.secret = SECRET
chromecast.app.id = APP_ID
 hoe this will help you

**Comment by somenath1435** [comment]
@spielers I've already sent an email to support@amahi.org but haven't got any reply

**Comment by spielers** [comment]
@somenath1435 ask in IRC Channel

**Comment by somenath1435** [comment]
@cpg @octacode @balaji-ramavathu please suggest what to do
