### ISSUE TITLE
Useless DropDown 

### ISSUE THREAD

**Issue by preadatorshek** [amahi/android#506]
**Describe the issue**

**Describe the issue**
  In the Navigation Section there is a Dropdown Menu on the top Named as Welcome to Amahi!
   That is completely useless not only it looks ugly but this is no code to be procced while tapping on       
    Welcome to Amahi.

**Expected behavior**

There is no need of the Dropdown 

**Screenshots**

![Amahi Issue](https://user-images.githubusercontent.com/48478876/73135595-df47f480-4069-11ea-932d-6a528e9976e1.jpeg)

*

**Comment by octacode** [comment]
Hi @preadatorshek 
This dropdown is used for switching between HDAs. Its an important feature of the app
