### ISSUE TITLE
App crashed with landscape as well as Query issue(Myntra)

### ISSUE THREAD

**Issue by shrootis** [amahi/android#507]
App crashed on reopening as there was a problem in setDelay method as far as i can judge plus there is some problem with sql querry.
error in generating contents from myntra.com

**Comment by shrootis** [comment]
This is my first attempt of learning how to find bugs and other issues.Please help me in doing so....

**Comment by spielers** [comment]
@shrootis check the logs

**Comment by chirag-jn** [comment]
Can you elaborate further on this issue @shrootis

**Comment by cpg** [comment]
Please post an exact url that shows this issue and reopen if you still experience it.
