### ISSUE TITLE
Create responsive landscape activity for intro

### ISSUE THREAD

**Issue by dipu989** [amahi/android#509]
**Describe the issue**
Intro activity is not responsive in landscape mode.

**To Reproduce or Feature details**
1. Switch the app in landscape mode.
2. Start the intro and check the first screen.

**Expected behavior**
The screen should be scrollable so that the user can view the instructions properly.

**Screenshots**
![Screenshot_2020-02-25-17-17-45-27_8f7f52555d974a92fa29728873f61978](https://user-images.githubusercontent.com/31280303/75246054-fc045300-57f4-11ea-93dd-47ab5ed072e0.png)

**Comment by dipu989** [comment]
I will fix this issue!

**Comment by samarth30** [comment]
hey @dipu989  I have also installed the application and ran it on horizontal view but the intro view pager is running just fine without any error. I think you have installed the application from the playstore rather than installing beta version of the amahi application from this repository.

I hope this would help you

**Comment by dipu989** [comment]
@samarth30 I have installed the app from the GitHub repository.

**Comment by AkshobhyaP** [comment]
Hey @dipu989 how did you get the api.properties value required to build the application. I am unable to login without them. It would mean a lot if you helped out. Thank you.

**Comment by spielers** [comment]
@dipu989 I checked the app it's working perfectly fine in horizontal view the page is also scrollable

**Comment by spielers** [comment]
Hey @AkshobhyaP send a message to support@amahi.org and they will provide you 
amahi = URL
url.proxy = URL
client.id = ID
client.secret = SECRET
chromecast.app.id = APP_ID


hope this will help you.

**Comment by chirag-jn** [comment]
I think that @samarth30 is right. I am not facing any issue either in landscape mode. Can you please mention your screen's resolution and ppi too @dipu989 ?

![amahi_landscape](https://user-images.githubusercontent.com/31701616/77123182-665f8a80-6a65-11ea-9deb-e4066a339006.jpg)
