### ISSUE TITLE
No checks on username TextField if it contains spaces.

### ISSUE THREAD

**Issue by developershutt** [amahi/android#511]
In Authentication class there's no condition that checks if username contains spaces before authentication.

**Comment by developershutt** [comment]
![Screenshot_20200228-163334](https://user-images.githubusercontent.com/20475549/75543901-d7081e00-5a48-11ea-8d22-86c3566ae37b.png)

**Comment by developershutt** [comment]
I've created PR #510 that fixes this issue

**Comment by chirag-jn** [comment]
In this case, the app says "The Username or Password are incorrect". I hope that is sufficient.

**Comment by chirag-jn** [comment]
Related PR #592
