### ISSUE TITLE
Unable to access some items in Navigation Drawer

### ISSUE THREAD

**Issue by samarth30** [amahi/android#513]
**Description of the issue**
In the landscape mode in the Navigation Activity in navigation drawer I am unable to scroll down to access item as of now there are not items but in future when friending feature will be introduced then it will not be accessable in landscape mode

**Screenshots**
<a href="https://imgflip.com/gif/3rhaw3"><img height="300" src="https://i.imgflip.com/3rhaw3.gif" title="made at imgflip.com"/></a>

**Smartphone :**
 - Device: oppo realme
 - OS:  9

**Comment by AkshobhyaP** [comment]
Hey @samarth30 , from where can i get the credentials required to build the application.
