### ISSUE TITLE
Replace the actionbar with a toolbar

### ISSUE THREAD

**Issue by megabitdragon** [amahi/android#52]
This is self explanatory. Replace the actionbar with a toolbar using the support library.

**Comment by octacode** [comment]
Can I work on this issue?
Thanks

**Comment by megabitdragon** [comment]
Give it a try.

**Comment by cpg** [comment]
can this be closed?

**Comment by octacode** [comment]
@cpg I am working on it and will be sending a PR very soon.

**Comment by joydeepsaha05** [comment]
@octacode Could I take this? I've done most of the changes to convert the ActionBar.

**Comment by octacode** [comment]
@joydeepsaha05 . I have already sent a PR #67 but it had a lot of merge conflicts. So I closed it. I too am already done with the code and will be sending the PR very soon.
Thanks

**Comment by octacode** [comment]
@cpg @joydeepsaha05 While I was working on it noticed that we don't actually need custom Toolbars in our case because we're able to deliver the same experience with the support Action bar which really is awesome. Moving onto custom Toolbars will just complicate the code. 
So I guess we can close this one.

**Comment by joydeepsaha05** [comment]
@octacode @cpg The only thing I don't like about the current implementation is the logo. It looks a bit wierd and takes up a lot of space.

**Comment by octacode** [comment]
@joydeepsaha05 so I guess we can simply replace the info  from ic_launcher in the action bar to another 32 bit PNG alpha image.

**Comment by joydeepsaha05** [comment]
@cpg I've replaced the back arrow with the launcher icon. In my opinion, it does look better but I think it doesn't follow the material design guidelines. Opinions?

![device-2017-04-09-084905](https://cloud.githubusercontent.com/assets/12814192/24834412/b6115fa4-1d01-11e7-8ce5-316e36eff25e.png)

**Comment by cpg** [comment]
Hmm. It does not look good to me. What we have is a little suboptimal, but this is too tight between the indicator and the logo. Is there anything else besides that space and the different symbol for the indicator?

**Comment by joydeepsaha05** [comment]
I could increase the space between the back indicator and the logo. But, do we really need the logo to be present in the action bar?

**Comment by octacode** [comment]
That's what I was thinking about. It would be better if we don't have the Amahi logo in the action bar.

**Comment by cpg** [comment]
too old, we did something else.
