### ISSUE TITLE
UI no Changes for selecting menu item

### ISSUE THREAD

**Issue by Ahmed-Abd-Elsamie** [amahi/android#520]
Select item from side menu problem

Selection color doesn't changes when select item Apps or Shares

Problem 
![Screenshot_2020-03-08-13-59-09-448_org amahi anywhere](https://user-images.githubusercontent.com/41450463/76162769-49fc4d80-6149-11ea-897f-088486a6f01f.jpg)

While it should be like this when selecting apps
![Screenshot_2020-03-08-14-31-00-485_org amahi anywhere](https://user-images.githubusercontent.com/41450463/76162836-c98a1c80-6149-11ea-885e-bac2fe33ec19.jpg)

and like this when selecting Shares
![Screenshot_2020-03-08-14-30-46-716_org amahi anywhere](https://user-images.githubusercontent.com/41450463/76162850-dc9cec80-6149-11ea-928e-87ed3ac8ce38.jpg)

**Comment by zedlabs** [comment]
I think this has been fixed in the beta branch, the screenshot is from the production version.

**Comment by chirag-jn** [comment]
This issue doesn't exist in the beta version and will be fixed in next production release.

**Comment by cpg** [comment]
It's fixed in the `beta` branch. Set for release. Closing. Thanks for reporting it.
