### ISSUE TITLE
Should be Using Handler for the Splash Screen which is more Efficient then the current process which is being used 

### ISSUE THREAD

**Issue by nileshteji** [amahi/android#524]
**Describe the issue**
A clear and concise description of what the bug/feature is.

**To Reproduce or Feature details**
4. See error or expected behavior

**Expected behavior**

**Screenshots**

**Smartphone (please complete as much of the following information as possible):**

**Additional context**

**Comment by nileshteji** [comment]
No need of Splash Activity Because we are not using the Application

**Comment by nileshteji** [comment]
Also I am not getting the flow of the project splash screen should be shown with some design on it or animation and we should have method to check a user is already logged in or not.For this i need to have chat with you sir 


The flow Should be as Follows:

if user is not logged in; 
Splash->Authentication->Navigation


if user is logged in 
Splash->Navigation

For This we need to have a method which have to be called in the splash Activity.So Sir what do you think about the issue should i start working on it

**Comment by chirag-jn** [comment]
Please follow discussion in PR #526

**Comment by cpg** [comment]
This first comment in the issue posts the template as is without specifying details. Reopen if it's still an issue please.
