### ISSUE TITLE
User behavior issue with spaces in Login

### ISSUE THREAD

**Issue by chirag-jn** [amahi/android#525]
**Describe the issue**
When we try to login in the app, if we have whitespace on the right of the username (which weren't supposed to be there), login still works.

**To Reproduce or Feature details**
1. Enter your username and password which should work fine.
2. Before pressing the sign in button, enter any amount of whitespace on the right. 
3. Try signing in.
4. It should signin successfully.

**Expected behavior**
It should show an error message that "The username or password are not correct."

**Smartphone**
 - Device: Vivo 1807
 - OS: Android 8.1

**Comment by chirag-jn** [comment]
@cpg @megabitdragon @octacode 
Can you please tell what would be the best fix for this issue?
We can just ignore the whitespace in the end and strip it before sending the login request further. If that fix works, then please let me know. I would love to go forward and implement the same.

**Comment by chirag-jn** [comment]
#511 talks about handling spaces in the username. That would certainly fix this issue too. But that won't explain why this issue exists in the first place.

**Comment by Soroyesodiq** [comment]
@chirag-jn the source code uses trim() method which removes the spaces and returns the omitted string when users click the sign in button. This is the ethical way of authenticating logins.

**Comment by chirag-jn** [comment]
You are right @Soroyesodiq It's ethical and valid of authenticating usernames. However, it was only working for trailing whitespaces and not leading whitespaces. I'll surely look into this further. Thanks for pointing out!

**Comment by chirag-jn** [comment]
This issue doesn't exist anymore, hence can be closed.
