### ISSUE TITLE
Connection Error after updating my fork 

### ISSUE THREAD

**Issue by DoMINAToR98** [amahi/android#55]
I'm facing an error on the login page
![screenshot at mar 09 14-15-29](https://cloud.githubusercontent.com/assets/22031769/23742467/e58f3784-04d2-11e7-8da8-637d80f81b00.png)
  HTTP FAILED: java.net.ConnectException: Failed to connect to api.amahi.org/208.115.201.202:443 after updating my fork

**Comment by cpg** [comment]
We are having some outages on the site. Unfortunately, and unlike in iterations before, we cannot tell very well what is happening (errors in the site, DoS attacks, etc.), and we're busy with some travel, so, for the time being, please try again.

Reopen if it persists.
