### ISSUE TITLE
No `RETRY` button on hda selection screen

### ISSUE THREAD

**Issue by csoni111** [amahi/android#60]
![hda_selection_screen](https://cloud.githubusercontent.com/assets/15021142/23754895/9eac0626-0504-11e7-9e94-41cbf89ec3a6.png)

There is no retry button present in this side navigation bar. If the fetching of hda list from the server fails for some reason, there is only one option that is to close the app and reopen again.

This happens a lot with me and it is irritating. So I would like to implement this feature. Suggest if a `Button` should be added or `SwipeRefreshLayout`.

**Comment by vjs3** [comment]
IMHO opinion SwipeRefreshLayout would better, in terms of UI/UX as well as latest guides.

**Comment by sukhbir-singh** [comment]
I would recommend making try again text as a clickable link. On clicking of which will refresh the screen.

**Comment by hshrimali** [comment]
@sukhbir-singh But the thing is that this "Connection Error" not only appears in the navigation drawer but also when we click on the Shares menu in navigation drawer and it doesn't open. So, I think, we can't add try again button eveywhere we get "Connection Error". So, I'll go with the idea of @vjs3 .

**Comment by sukhbir-singh** [comment]
Yes, I agree with you @hshrimali. SwipeRefreshLayout must be implemented in main screen.
But also In case navigation itself donot load then also user should have need an option to load.

**Comment by octacode** [comment]
Ya.. having a SwipeRefreshLayout in the NavigationDrawer itself is quite cumbersome. I too would recommend having a button.

**Comment by csoni111** [comment]
I tried both ways and the swipeRefreshLayout looks more efficient and cooler than a button to me. I have implemented the same in #68.

Thanks for your suggestions! :)

**Comment by cpg** [comment]
In my view, a button (or some link) takes space. A PDTR action is generally as intuitive and it takes no space. Merged.
