### ISSUE TITLE
Offline Files and Recent Files not Syncing with Server

### ISSUE THREAD

**Issue by chirag-jn** [amahi/android#600]
**Describe the issue**
If I delete a file from the server, it's not removed from the Recent Files and Offline Files screen.

**To Reproduce or Feature details**
1. Upload a file to the server and try to access it from the list of shares.
2. The file will be visible in Recent files activity which is expected behaviour.
3. Delete that particular file from the server.
4. That file will still be visible in Recent files.

**Expected behavior**
I'm not sure about this. Should the file be removed from recent files too? Is it expected behaviour?

**Screenshots**
![error_2](https://user-images.githubusercontent.com/31701616/89719701-b923e980-d9e8-11ea-9ddd-7ab4e6a213ab.gif)

**Comment by chirag-jn** [comment]
If I delete a file from the server, it is still accessible from the Offline Files activity and Recent files activity.

**Comment by cpg** [comment]
The app does not do syncing, so files downloaded should still be accessible on the device. This is a valid use case.
