### ISSUE TITLE
Increase font size of titles on Settings Screen/Activity

### ISSUE THREAD

**Issue by Akash-Ramjyothi** [amahi/android#616]
### Feature Request:
Currently, in the settings screen, the titles of the respective containers appear to be smaller than the actual content inside them. If there was a feature to relatively increase the size of the title, it would be better.

![Screenshot_2020-08-12-02-20-52-78_8f7f52555d974a92fa29728873f61978 (1)](https://user-images.githubusercontent.com/54114888/89949719-fc2ec880-dc45-11ea-8044-efcc3a0c994b.jpg)

**Comment by chirag-jn** [comment]
I guess that's what material design follows. 

![Screenshot_20200812_030439](https://user-images.githubusercontent.com/31701616/89951261-ba535180-dc48-11ea-82f9-e448b30d954c.jpg)
