### ISSUE TITLE
No Thumbnail on shares folders

### ISSUE THREAD

**Issue by RGlass89** [amahi/android#619]
**Describe the issue**
If I select welcome to Amahi on the app I get the thumbnail but if I go to a share on my server I don't get any thumbnail,  I remember that this used to work on the app , I know it used to take time to create them but that was no problem 

**To Reproduce or Feature details**
Steps to reproduce the behavior
1, open a the app
2. Select a share on you server that has images on it and it will create the thumbnail 

**Expected behavior**

**Screenshots**
This one is from the demo 
![Screenshot_20200813-191926_Amahi.jpg](https://user-images.githubusercontent.com/28194743/90172520-09110080-dd9b-11ea-82c3-664848e722cc.jpg)

This one from a share on the share only got about 4 images on that share
![Screenshot_20200813-192110_Amahi.jpg](https://user-images.githubusercontent.com/28194743/90172616-32ca2780-dd9b-11ea-9975-d372751d76f9.jpg)

**Smartphone (please complete as much of the following information as possible):**
 - Samsung 

**Additional context**
I am testing the new android app

**Comment by rahullli** [comment]
I would like to work on this issue .

**Comment by RGlass89** [comment]
Go for it
