### ISSUE TITLE
Addition of screen transitions

### ISSUE THREAD

**Issue by octacode** [amahi/android#62]
Right now we don't have any screen transitions between intents. I think it will be good to add a nice slide_in and slide_out transition effect during intent transitions. I would like to work on this issue.

**Comment by hshrimali** [comment]
@octacode If you don't mind can I handle this issue? Working on issues parallely will solve the issues in less time and we get more time to find the new ones.

**Comment by octacode** [comment]
@hshrimali Looks like I am already done with the code. However you can work on this issue #25. I'll be glad to help you out there.
