### ISSUE TITLE
Non-Constant Fields in Case Labels

### ISSUE THREAD

**Issue by chirag-jn** [amahi/android#683]
**Describe the issue**
With the introduction of Gradle 5.0, resource IDs won't be final anymore. Hence, a switch-case statement won't work in onClick function for view elements. We have to switch to if-else conditions of a view binding strategy for mapping resource IDs to their variables. 

More information: http://tools.android.com/tips/non-constant-fields

For the first case, we have to switch from
``` java
@Override
public void onClick(View view) {

    switch (view.getId()) {
        case R.id.next_btn:
            // Do something
            break;
    }
}
```
to something like this:
``` java
@Override
public void onClick(View view) {
    
    int id = view.getId();
    if (id == R.id.next_btn) {
        nextBtnPressed();
    }
}
```

Old view binding libraries like [JakeWharton/butterknife](https://github.com/JakeWharton/butterknife) won't work anymore either.

**Comment by Prakhar-Agarwal-byte** [comment]
@chirag-jn @cpg Hey can I work on this issue instead of Localisation Support? (#548 ).Please guide me where to start first as I new to code base of Amahi android.

**Comment by chirag-jn** [comment]
> @chirag-jn @cpg Hey can I work on this issue instead of Localisation Support? (#548 ).Please guide me where to start first as I new to code base of Amahi android.

Sure you can work on this.

**Comment by chirag-jn** [comment]
The Android documentation link would be a good place to let you know about the issue.

**Comment by Prakhar-Agarwal-byte** [comment]
@chirag-jn @cpg I have found 2 solutions for this issue. Please tell which is better so I can start implementing it.

1. A quick fix for this issue that we can disable NonConstantResourceId in module level build.gradle file. Code is given below -

`android {
    ...
    lintOptions {
        disable 'NonConstantResourceId'
    }
}`

2. Other fix is to replace all switch statements that use Non-Constant Fields in Case Labels with if else statements without effecting efficiency of code.

**Comment by chirag-jn** [comment]
In the first case, you are only disabling linting for NonConstantResourceId. That still leaves it as a pain point in future versions of Gradle. However, the second option seems great!

**Comment by Prakhar-Agarwal-byte** [comment]
@chirag-jn Okay I am implementing second option. Thanks for your suggestion!

**Comment by Prakhar-Agarwal-byte** [comment]
@chirag-jn @cpg I have sent a PR ( #685 ) for this issue please review it. I closed this PR due to some error.

**Comment by Prakhar-Agarwal-byte** [comment]
@chirag-jn @cpg This is the new PR( #689 ) for this issue please review it.
