### ISSUE TITLE
No patience

### ISSUE THREAD

**Issue by Prakhar-Agarwal-byte** [amahi/android#686]
@chirag-jn @cpg @Akash-Ramjyothi 
I want to build Amahi app for that I require an api.properties file. In the[ README.md](https://github.com/amahi/android/blob/beta/README.md) file, it is mentioned that I can get one by emailing but I didn't get any response from there. This issue is prohibiting new developers from contributing to Amahi android. Please look into this issue and provide a solution.
Thanks!

**Comment by Prakhar-Agarwal-byte** [comment]
@cpg Thanks a lot, Carlos. I am closing this issue.

**Comment by cpg** [comment]
Hi Prakhar,

It appears that you are not sensitive you privacy implications that are paramount to the Amahi community.

If you do this type of public posting of the emails of the team/support, in addition of incessant and unnecessarily alarming (urgent? cannot contribute?) when it appears that you _did not even install Amahi in a PC or a VM_ you will be banned from the Amahi community.

Best regards

**Comment by cpg** [comment]
Hi Prakhar,

It appears that you are not sensitive to privacy implications that are paramount to the Amahi community.

If you do this type of public posting of the emails of the team/support, in addition of incessant and unnecessarily alarming (urgent? cannot contribute?) when it appears that you did not even install Amahi in a PC or a VM you will be banned from the Amahi community.

While we appreciate contributions, we want to welcome to our community people that are attuned about the privacy implications of software that helps run a server with people's data in it.

Best regards

**Comment by Prakhar-Agarwal-byte** [comment]
@cpg Sorry, I am new to open source and I did not intend to violate anyone's privacy. I will take care of this incident next time. Once again my best intention was to contribute to the Amahi community, become a part of it and grow with it so I became a bit impatient. I will work with full dedication and contribute to Amahi android.

**Comment by chirag-jn** [comment]
> @cpg Sorry, I am new to open source, and I did not intend to violate anyone's privacy. I will take care of this incident next time. Once again, my best intention was to contribute to the Amahi community, become a part of it and grow with it, so I became a bit impatient. I will work with full dedication and contribute to Amahi android.

Please note that things might be a little slow, but they will happen eventually. Your contributions are continuously monitored and discussed on other platforms which aren't public, so it takes time to review things. 

Our goal is to make a great application and to ensure that we need multiple reviews before adding any single line of code.

**Comment by Prakhar-Agarwal-byte** [comment]
Okay, I understand.
Thanks.
