### ISSUE TITLE
Swipe to change song.

### ISSUE THREAD

**Issue by Ishmeetsingh97** [amahi/android#69]
I want to implement a feature which changes the song on swiping the AudioActivity just like done in Google Play Music. Can i work on it ?

**Comment by cpg** [comment]
This is a useful idea.

**Comment by Ishmeetsingh97** [comment]
Sure. I will send a PR soon.

**Comment by doomers** [comment]
@cpg can i work on this issue?

**Comment by csoni111** [comment]
As discussed in pr #212 following features need to be implemented:

- Pre fetching metadata for songs
- Implementing proper caching mechanism for song metadata (along with album art bitmap)
- Replacing Album art ImageView with ViewPager
- Thumbnail album art previews in place of icons for audio files

**Comment by Yasha08** [comment]
Hi, what is this app about? I'm a UX/UI designer and is looking to contribute. Is this a music player app?

**Comment by cpg** [comment]
[Read all about it](https://www.amahi.org/android), not surprisingly, with a quick search.

**Comment by ArihantJain456** [comment]
I would like to work on this.

**Comment by mohitsvnit** [comment]
@ArihantJain456 are you working on this?

**Comment by ArihantJain456** [comment]
ye

**Comment by mohitsvnit** [comment]
Because I already completed half of it.

**Comment by ArihantJain456** [comment]
I have also completed most of it, only linking metadata with viewpager is left.
you should ask first before working on it.

**Comment by mohitsvnit** [comment]
OK no problem. Actually I started working on it 3 days ago and that time nobody was working on it.

**Comment by ArihantJain456** [comment]
Then why you haven't comment?

**Comment by mohitsvnit** [comment]
Actually I thought no body is working on it. I didn't got notification that you commented. Sorry.

**Comment by cpg** [comment]
It's our fault for not confirming @ArihantJain456 as assigned to it. Too many things going on and it fll through the cracks. Please try and be cooperative. It's not a competition.
