### ISSUE TITLE
Adaptive icons for Android 8.0 and above

### ISSUE THREAD

**Issue by Prakhar-Agarwal-byte** [amahi/android#694]
**Describe the feature**
Adaptive icons were introduced in Android API level 26. Currently, the Amahi app does not have them and the adaptive icon will be nice to have feature for the latest android versions. 

**Feature details**
Feature details:
1. Works for Android 8.0 and above.
2. Improves user experience.

**Comment by YugN17** [comment]
is anyone working on this??

**Comment by YugN17** [comment]
@cpg @Prakhar-Agarwal-byte ?

**Comment by Prakhar-Agarwal-byte** [comment]
> is anyone working on this??

A Pull Request (#695 ) is already in review for this issue . So wait till it resolves.
