### ISSUE TITLE
SIGN UP??

### ISSUE THREAD

**Issue by DeepaliVerma011** [amahi/android#697]
**Describe the issue**
Need to have a sign up activity in the application to make it easy for users.

**To Reproduce or Feature details**
1. Make a sign up activity before sign in.
2.signup should contain a button to sign in page.
3. A skip option should also be there.

**Comment by DeepaliVerma011** [comment]
i want to do this work
aims :
to make a ui for sign up

**Comment by prabs3257** [comment]
is this issue open can i work on it ?? @DeepaliVerma011

**Comment by DeepaliVerma011** [comment]
i am working on this issue actually

**Comment by DeepaliVerma011** [comment]
i solved the issue. please check my PR

**Comment by chirag-jn** [comment]
Signing up users on the Amahi platform isn't as simple as signing up on the app. They have to first create an account at https://www.amahi.org/ and set up an HDA server. The credentials used to create the account are used to login in the app.

**Comment by chirag-jn** [comment]
Please refer #452 and #500

**Comment by cpg** [comment]
It's not constructive to have users of the app that may be noobs register and never install an HDA.

Installing an HDA is not light work and we do not want users that never install a system. It does not help anyone.

Sorry about the closing. It's a shame we could not use the great work you guys did.
