### ISSUE TITLE
Correction in Hindi Translation

### ISSUE THREAD

**Issue by Prakhar-Agarwal-byte** [amahi/android#703]
**Describe the issue**
There are some errors in the Hindi translation of strings. They should be corrected.

**To Reproduce or Feature details**
Look at some specific strings in Hindi that are incorrect.

**Expected behavior**
Correct strings must be displayed.

**Smartphone (please complete as much of the following information as possible):**
All devices with Hindi set as the primary language.

**Comment by imSanko** [comment]
I wanna work on to this project can you assign it to me.

**Comment by Prakhar-Agarwal-byte** [comment]
> I wanna work on to this project can you assign it to me.

@imSanko Hi! There is already a PR opened for this issue. You can instead look for other issues.
