### ISSUE TITLE
New Shimmer Loading Effect

### ISSUE THREAD

**Issue by Prakhar-Agarwal-byte** [amahi/android#712]
**Describe the feature**

A new type of loading popularly known as the "Shimmer Loading Effect" to replace Dancing Dots animation can be added. This type of loading is a new trend and has been proven to increase the user experience as it feels like the content is just a few microseconds away.
This similar inspiration is being followed by Facebook, Instagram, Youtube, and Payoneer too.

**Expected behavior**

![Shimmer-Feed-Demo](https://user-images.githubusercontent.com/17739006/102314671-d53c2680-3f98-11eb-9650-057482ea23d5.gif)

**Additional context**
We can use the library called "Facebook-Shimmer-Android" https://github.com/facebook/shimmer-android for implementing the loading effect. It is useful as an unobtrusive loading indicator that was originally developed for Facebook Home.
Link to the official page https://facebook.github.io/shimmer-android

**Comment by Prakhar-Agarwal-byte** [comment]
I am starting to work on this.

**Comment by deepak-prajapatii** [comment]
@cpg @Prakhar-Agarwal-byte Can I work on this issue?

**Comment by Prakhar-Agarwal-byte** [comment]
> @cpg @Prakhar-Agarwal-byte Can I work on this issue?
@deepak-prajapatii 
Hey! I have almost completed the issue. I am working on polishing the effect and refactoring the code. I will send a PR in 2-3 days. You can instead look for other issues. Thanks

**Comment by deepak-prajapatii** [comment]
> > @cpg @Prakhar-Agarwal-byte Can I work on this issue?
> @deepak-prajapatii 
> Hey! I have almost completed the issue. I am working on polishing the effect and refactoring the code. I will send a PR in 2-3 days. You can instead look for other issues. Thanks

@cpg okay
