### ISSUE TITLE
Need to change Actionbar title according to directory opened

### ISSUE THREAD

**Issue by sukhbir-singh** [amahi/android#72]
Fixed by PR #73

**Comment by octacode** [comment]
@sukhbir-singh I have already implemented it in my PR #67 earlier.

**Comment by sukhbir-singh** [comment]
@octacode I have reviewed every single line of your code in PR #67 . But you changes doesn't seems to be same as mine. In PR #73 I am changing the title bar as per folders like if user is in music folder title of action bar set to be music and so on, which is not incorporated in your PR. 

Also you PR #67 has not made any change in ServerFilesFragment.java file which is needed to fix this issue.
