### ISSUE TITLE
Vim api.properties error

### ISSUE THREAD

**Issue by doomers** [amahi/android#74]
Api.properties Error
url.amahi = URL
url.proxy = URL
client.id = ID
client.secret = SECRET

@megabitdragon  @cpg where to get these keys from?

**Comment by hshrimali** [comment]
@doomers You can ask this query on irc channel. You will get your answers there. These keys are kept private due to some security reasons. Okay.

**Comment by doomers** [comment]
okay @hshrimali i have dropped a message on irc .

**Comment by megabitdragon** [comment]
Please use the google group for these requests.

**Comment by doomers** [comment]
@megabitdragon i have posted these in google groups 2 days back, but no one replied me there.
if would be great if you can mail me .
my email id is rahul40800@gmail.com
