### ISSUE TITLE
Adding more features to Video Player

### ISSUE THREAD

**Issue by csoni111** [amahi/android#76]
I would like to add some more features to the video player. 

- *Subtitles View* along with dialog fragment to select the subtitles file
- ~~*Screen Gestures*:~~
    - ~~swipe up/down on left to increase/decrease screen brightness~~
    - ~~swipe up/down on right to increase/decrease volume~~
    - ~~swipe left/right to seek the video~~
- ~~Showing the progress bar while *buffering* the video from remote~~

Suggest if any more features are required and can be added?

**Comment by ak2711** [comment]
video player currently works in portrait orientation.features to change orientation can be added.Features like automatic screen change on tilting screen can also be included.

**Comment by csoni111** [comment]
Yes, I actually thought that! Thanks for the suggestion anyway. Will add that also!

**Comment by csoni111** [comment]
Closing it as the UI for subtitles has been covered in #224 and rest has been implemented.
