### ISSUE TITLE
Adding media controls to notification bar for controlling music play

### ISSUE THREAD

**Issue by sukhbir-singh** [amahi/android#79]
I want to work on this issue.
If someone else is already completed his work on this issue please do notify me, I will work on something else.

**Comment by Ishmeetsingh97** [comment]
Hi, are you still working on the same ? If not, i'd like to. Please ping me asap.

**Comment by sukhbir-singh** [comment]
Yes I am still working on this issue, Right now I am facing the same problem as described on #99 
I will try to set up my own amahi server then continue with this.

**Comment by cpg** [comment]
No action.
