### ISSUE TITLE
ContentDescription for buttons : Accessibility feature of Android

### ISSUE THREAD

**Issue by Ishmeetsingh97** [amahi/android#82]
ContentDescription for the buttons is for the Accessibility Features of Android. The contentDescription is what get's read back to the (assumingly blind or hard-of-sight user) so they have an idea of what the picture is since they aren't able to view it.
Can i send a PR for this ?

**Comment by cpg** [comment]
Sure, go ahead.

**Comment by gopikaharikumar** [comment]
May I work on this issue?
