### ISSUE TITLE
Server Api returns size as 0 for folders containing some files

### ISSUE THREAD

**Issue by csoni111** [amahi/android#83]
While testing the app, I have found a bug in the api. It returns **0 file size** for folders/directories inside a share even when they contain files inside them. I am not sure if it is a bug or it was meant that way.

**Comment by cpg** [comment]
It was meant that way.

What should the size of a folder be?

Similar with symlinks.

Number of files does not really help much, generally speaking, so we opted for 0. With a good reason we could change that.
