### ISSUE TITLE
App is crashing on changing Orientation in login Screen 

### ISSUE THREAD

**Issue by doomers** [amahi/android#87]
App is crashing on changing the Orientation in Login Screen.

Screenshots :

![screenshot_20170316-225923](https://cloud.githubusercontent.com/assets/11586392/24010142/01cf7c2c-0a9d-11e7-9ecf-281f52aefd46.png)

![screenshot_20170316-225927](https://cloud.githubusercontent.com/assets/11586392/24010150/09935866-0a9d-11e7-8130-2bf284e19e54.png)

@cpg this is needed to be fix as soon as possible.
shall i send a PR for this?

**Comment by cpg** [comment]
I think @csoni111 identified it in a [bad identifier here](https://github.com/amahi/android/commit/af02dd2583eff5e10344ab9fb94e820ec3606b2a#commitcomment-21351424), but sure.

**Comment by cpg** [comment]
Created a wiki page for [checklist for new releases](https://github.com/amahi/android/wiki/Checklist-for-releases) so that we remember to test everything and we do not miss things like this.

Feel free to contribute.

**Comment by doomers** [comment]
Okay I am working on it, will create a PR tomorrow

**Comment by csoni111** [comment]
@cpg the one that I mentioned [here](https://github.com/amahi/android/commit/af02dd2583eff5e10344ab9fb94e820ec3606b2a#commitcomment-21351424) is another bug. In that opening the `apps` page crashes the app.

This one is happening because there are two layout for the login screen, one for the `portrait mode` and another for `landscape mode`. Now in pr #81 @Ishmeetsingh97 made the layout changes only for portrait one. The landscape one is still older. Hence the crash.

**Comment by sukhbir-singh** [comment]
Yes as explained by @csoni111, you need to make same changes to landscape mode as made in portrait mode by PR #81
The app is getting Null pointer exception because of unavailability of TextInputLayout.getEditText() in landscape mode.

**Comment by doomers** [comment]
@sukhbir-singh Yes i know ,i have already figured it out, 
And started working on it, i will send the PR tomorrow.

**Comment by csoni111** [comment]
@doomers while you are on this, pls make one more change! The [Username field](https://github.com/amahi/android/pull/81/files#diff-293e30bb0d968c8a108574a8a561b3deR41) is still `EditText` while the [Password field](https://github.com/amahi/android/pull/81/files#diff-293e30bb0d968c8a108574a8a561b3deR52) was changed to `TextInputLayout`. 
So change the username field also to `TextInputLayout`. That way it will look better!

**Comment by csoni111** [comment]
@doomers so sorry for solving the issue that you mentioned and asked to do. But @cpg asked me to complete it asap, as another issue was pending because of this.

**Comment by cpg** [comment]
@doomers please review #90 when you can. I asked @csoni111 to work on this because it was blocking something else for me.

**Comment by doomers** [comment]
@cpg @csoni111 no problem if this issue is needed to be solved asap, but I was unaware that you had also a PR when I made this PR, but now as I have done it in #91, it would be great if you can merge mine first
and work on issue after the merge and create a separate PR, as it would a transparency of what changes have been done in which PR, as your PR is not reflecting that you have fixed any Orientation based changes

**Comment by csoni111** [comment]
@doomers, @cpg : The app built by the code in the current master branch, still crashes on logging in while in `landscape mode`. I shall try to fix this issue in my currently open pr #90.

Also there is another bug that I found, shall open a new issue for that!

**Comment by cpg** [comment]
Oops, landscape is still still crashing.

**Comment by doomers** [comment]
@cpg @csoni111  but it is now working fine in my device, Can you share the logcat or Screenshots here.

**Comment by csoni111** [comment]
Sorry to bother everyone, I think I might have tested the code from other branch. Just got confused with all the code changes.
It works fine now. This issue can be closed @cpg.
