### ISSUE TITLE
App crashes on clicking on the `Apps` tab in the side nav bar

### ISSUE THREAD

**Issue by csoni111** [amahi/android#88]
As commented [here](https://github.com/amahi/android/commit/af02dd2583eff5e10344ab9fb94e820ec3606b2a#commitcomment-21351424) the app crashes on opening `Apps` tab.
Should I send a new pr for correcting this or the old pr #34 (which made this change) should be reverted back and the commits to be edited? @cpg

**Comment by cpg** [comment]
I think someone is working on it in #87. Let's focus on that there.

**Comment by csoni111** [comment]
@cpg that one is a different bug then this one! This one happens on opening the `Apps` tab. That one happens on switching to `Landscape mode` (or rotating the device) in login screen.

The two are totally different bugs!
