### ISSUE TITLE
Adding support for AppCompatActivity

### ISSUE THREAD

**Issue by octacode** [amahi/android#96]
For the time being the activities don't support AppCompatActivity. 

**Benefits of using AppCompatActivity**

It not only provide backwards compatibility to our app but also provides us the access to the Material Design Library too. After this we can easily add FloatingActionButtons, Snackbars, AlertDialogBoxes and other material design widgets easily which now we can't.

I'd be working on it.

**Comment by adithya321** [comment]
Are you still working on this? If not, I would like to start working on it.

**Comment by octacode** [comment]
Yes! I am working on the and soon will send a PR.
