### ISSUE TITLE
Not showing complete picture after zoom.

### ISSUE THREAD

**Issue by hshrimali** [amahi/android#97]
After complete zoom of a picture, when we swipe left to see till the right most part of the image, it just changes the picture instead of showing the right part of the picture which I think should not happen.

**Comment by csoni111** [comment]
I don't think so this is the case. It works fine for me. Here is the [code](https://github.com/amahi/android/blob/master/src/main/java/org/amahi/anywhere/view/TouchImageView.java#L121) that disallows the view pager to change the image while there is some portion of the image still left to display. I have kept the difference between `Maximum translation possible in X` and `Current translation in X` as 0.5, for the check to enable the ViewPager to change the image. Keeping it to 0 would result in another problem as one may not be able to reach the exact boundary. 

I had wasted hours to figure it out initially while implementing this but now according to me it works fine.

**Comment by csoni111** [comment]
Can you attach a screenshot of the zoomed in image while swiping left (and the ViewPager changing the image) and also the original image (with no zoom)? So that the issue can be clearly understood!

**Comment by hshrimali** [comment]
@csoni111  app is still showing the Connection Error problem. So, I can't enter that image folder to show you the screenshot. As soon as the connection comes I will send you the screenshot

**Comment by hshrimali** [comment]
Okay @csoni111 Look at the screenshots.

The below one is while trying to see till the right most part of the picture but it changed.

![screenshot_20170319-171523](https://cloud.githubusercontent.com/assets/17125712/24080554/eca4fdae-0cc7-11e7-902f-20bcad7bbc70.jpg)

And this one is the complete first picture

![screenshot_20170319-171537](https://cloud.githubusercontent.com/assets/17125712/24080558/188aa6f8-0cc8-11e7-8d05-c4681b72e5bc.jpg)

**Comment by csoni111** [comment]
@hshrimali I cannot reproduce this! But if you are facing such an issue then there must be something that I might have overlooked in the code.

Can you please debug the code? You just have to log the values of `absTransX` _(this is the current absolute translation in X direction)_ and `transXMax` _(this is the maximum translation possible till the complete image is shown)_. You will find these two variables [here](https://github.com/amahi/android/blob/master/src/main/java/org/amahi/anywhere/view/TouchImageView.java#L117). 

Now for the correct functionality, until the `abxTransX` reaches the `transXMax` (ie the extreme part of the image is displayed) the touch event interception by the viewpager must be [disallowed](https://github.com/amahi/android/blob/master/src/main/java/org/amahi/anywhere/view/TouchImageView.java#L123). Disallowing the view pager to intercept the touch event will not allow it to change the image and so the image will be scrolled inside the current frame only.

So after logging the values please check if this functionality is maintained in your case. I hope all this is understandable!

**Also anyone else if facing this issue, please comment!**

**Comment by cpg** [comment]
I cannot reproduce it either.
