### ISSUE TITLE
Connection error when whenever i try to open shares folder

### ISSUE THREAD

**Issue by Ishmeetsingh97** [amahi/android#99]
I cant access the demo files and getting this error time and again. How to fix this ?
![screenshot_20170317-190400](https://cloud.githubusercontent.com/assets/16138298/24045467/3cdff4f6-0b45-11e7-8442-7a0dab20038c.png)

**Comment by doomers** [comment]
I am getting the same issue from last 2-3 hours, 
I think there is some issue with the servers or may be something else.

**Comment by Ishmeetsingh97** [comment]
Yes there mayb an issue with the server but i am getting this error since yesterday? Any other way to get started with debugging the app ?

**Comment by octacode** [comment]
@doomers @Ishmeetsingh97 This happenes quite often. As @cpg once mentioned that there are people already at Amahi trying to fix the issue.

Try settings your own Amahi server.
[https://wiki.amahi.org/index.php/Main_Page](https://wiki.amahi.org/index.php/Main_Page)
can close this one.

Thanks
